--liquibase formatted sql
--changeset dmarotta:20250326_152438_caca_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE categorie_catasto DISABLE ALL TRIGGERS;

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A01', 'ABITAZIONI DI TIPO SIGNORILE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A02', 'ABITAZIONI DI TIPO CIVILE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A03', 'ABITAZIONI DI TIPO ECONOMICO', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A04', 'ABITAZIONI DI TIPO POPOLARE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A05', 'ABITAZIONI DI TIPO ULTRAPOPOLARE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A06', 'ABITAZIONI DI TIPO RURALE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A07', 'ABITAZIONI IN VILLINI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A08', 'ABITAZIONI IN VILLE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A09', 'CASTELLI, PALAZZI DI EMINENTI PREGI ARTISTICI O STORICI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A10', 'UFFICI E STUDI PRIVATI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('A11', 'ABITAZIONI O ALLOGGI TIPICI DEI LUOGHI (TRULLI, RIFUGI DI MONTAGNA, BAITE, ECC.)', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B01', 'COLLEGI E CONVITTI, EDUCANDATI, RICOVERI, ORFANOTROFI, OSPIZI, CONVENTI, SEMINARI, CASERME', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B02', 'CASE DI CURA E OSPEDALI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B03', 'PRIGIONI E RIFORMATORI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B04', 'UFFICI PUBBLICI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B05', 'SCUOLE, LABORATORI SCIENTIFICI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B06', 'BIBLIOTECHE, PINACOTECHE, MUSEI, GALLERIE, ACCADEMIE CHE NON HANNO SEDE IN EDIFICI DELLA CATEGORIA A09', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B07', 'CAPPELLE ED ORATORI NON DESTINATI ALL''ESERCIZIO PUBBLICO DEL CULTO', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('B08', 'MAGAZZINI SOTTERRANEI PER DEPOSITI DI DERRATE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C01', 'NEGOZI E BOTTEGHE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C02', 'MAGAZZINI E LOCALI DI DEPOSITO', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C03', 'LABORATORI E LOCALI DI DEPOSITO', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C04', 'FABBRICATI PER ARTI E MESTIERI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C05', 'STABILIMENTI BALNEARI E DI ACQUE CURATIVE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C06', 'STALLE, SCUDERIE, RIMESSE. AUTORIMESSE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('C07', 'TETTOIE CHIUSE O APERTE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D01', 'OPIFICI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D02', 'ALBERGHI E PENSIONI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D03', 'TEATRI, CINEMATOGRAFI, SALE PER CONCERTI E SPETTACOLI E SIMILI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D04', 'CASE DI CURA E OSPEDALI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D05', 'ISTITUTI DI CREDITO, CAMBIO E ASSICURAZIONE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D06', 'FABBRICATI E LOCALI PER ESERCIZI SPORTIVI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D07', 'FABBRICATI COSTRUITI O ADATTATI PER LE SPECIALI ESIGENZE DI UN''ATTIVITA` INDUSTRIALE E NON SUSCETTIBILI DI DESTINAZIONE DIVERSA SENZA RADICALI TRASFORMAZIONI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D08', 'FABBRICATI COSTRUITI O ADATTATI PER LE SPECIALI ESIGENZE DI UN''ATTIVITA` COMMERCIALE E NON SUSCETTIBILI DI DESTINAZIONE DIVERSA SENZA RADICALI TRASFORMAZIONI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D09', 'EDIFICI GALLEGGIANTI O SOSPESI ASSICURATI A PUNTI FISSI DEL SUOLO, PONTI PRIVATI SOGGETTI A PEDAGGIO', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D10', 'RESIDENCE', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D11', 'SCUOLE E LABORATORI SCIENTIFICI PRIVATI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('D12', 'POSTI BARCA IN LUOGHI TURISTICI, STABILIMENTI BALNEARI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F06', 'FABBRICATO IN ATTESA DI DICHIARAZIONE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F07', 'INFRASTRUTTURE DI RETI PUBBLICHE DI COMUNICAZIONE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E01', 'STAZIONI PER SERVIZI DI TRASPORTO TERRESTRI, MARITTIMI ED AEREI', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E02', 'PONTI COMUNALI E PROVINCIALI SOGGETTI A PEDAGGIO', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E03', 'COSTRUZIONI E FABBRICATI PER SPECIALI ESIGENZE PUBBLICHE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E04', 'RECINTI CHIUSI PER SPECIALI ESIGENZE PUBBLICHE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E05', 'FABBRICATI COSTITUENTI FORTIFICAZIONI E LORO DIPENDENZE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E06', 'FARI, SEMAFORI, TORRI PER RENDERE D''USO PUBBLICO L''OROLOGIO COMUNALE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E07', 'FABBRICATI DESTINATI ALL''USO PUBBLICO DEI CULTI', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E08', 'FABBRICATI E COSTRUZIONI NEI CIMITERI, ESCLUSI I COLOMBARI, I SEPOLCRI E LE TOMBE DI FAMIGLIA', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('E09', 'EDIFICI A DESTINAZIONE PARTICOLARE NON COMPRESI NELLE CATEGORIE PRECEDENTI DEL GRUPPO E', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F01', 'AREE URBANE SENZA FABBRICATI PERMANENTI', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F02', 'UNITÀ COLLABENTI', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F03', 'UNITÀ IN CORSO DI COSTRUZIONE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F04', 'UNITÀ IN CORSO DI DEFINIZIONE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('F05', 'LASTRICO SOLARE', 'S', 'N');

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('T', 'TERRENI', 'S', null);

insert into categorie_catasto (CATEGORIA_CATASTO, DESCRIZIONE, FLAG_REALE, ECCEZIONE)
values ('T2', 'TERRENI RIDOTTI', 'S', null);

ALTER TABLE categorie_catasto ENABLE ALL TRIGGERS;
