--liquibase formatted sql
--changeset dmarotta:20250326_152438_cata_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE carichi_tarsu DISABLE ALL TRIGGERS;

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2019, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2020, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, 'S', null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2022, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, 'S', null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2023, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, 'S', null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2025, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, 'S', 'T', null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2018, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2012, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, null, null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2013, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, 0.30, null, 1, null, null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2014, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, null, null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2015, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, null, null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2016, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2017, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, null, null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2024, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, 'S', null, null, null);

insert into carichi_tarsu (ANNO, ADDIZIONALE_ECA, MAGGIORAZIONE_ECA, ADDIZIONALE_PRO, COMMISSIONE_COM, NON_DOVUTO_PRO, COMPENSO_MINIMO, COMPENSO_MASSIMO, PERC_COMPENSO, LIMITE, TARIFFA_DOMESTICA, TARIFFA_NON_DOMESTICA, ALIQUOTA, FLAG_LORDO, FLAG_SANZIONE_ADD_P, FLAG_SANZIONE_ADD_T, FLAG_INTERESSI_ADD, MESI_CALCOLO, IVA_FATTURA, MAGGIORAZIONE_TARES, FLAG_MAGG_ANNO, MODALITA_FAMILIARI, FLAG_NO_TARDIVO, ENTE, FLAG_TARIFFE_RUOLO, RATA_PEREQUATIVE, FLAG_TARIFFA_PUNTUALE, COSTO_UNITARIO)
values (2021, 0.00, 0.00, 5.00, null, null, null, null, null, null, null, null, null, 'S', 'S', null, 'S', 0, null, null, null, 1, 'S', null, 'S', null, null, null);

ALTER TABLE carichi_tarsu ENABLE ALL TRIGGERS;
