--liquibase formatted sql
--changeset dmarotta:20250326_152438_cc_diritti_ins stripComments:false
--validCheckSum: 1:any

Insert into cc_diritti values ('10','Proprietà');
Insert into cc_diritti values ('1s','Proprietà superficiaria');
Insert into cc_diritti values ('1t','Proprietà per l`area');
Insert into cc_diritti values ('20','Nuda proprietà');
Insert into cc_diritti values ('2s','Nuda proprietà superficiaria');
Insert into cc_diritti values ('30','Abitazione');
Insert into cc_diritti values ('3 ','Comproprietario');
Insert into cc_diritti values ('3s','Abitazione su proprietà superficiaria');
Insert into cc_diritti values ('40','Diritto del concedente');
Insert into cc_diritti values ('4 ','Comproprietario per');
Insert into cc_diritti values ('50','Enfiteusi');
Insert into cc_diritti values ('60','Superficie');
Insert into cc_diritti values ('70','Uso');
Insert into cc_diritti values ('7 ','Comproprietario del fabbricato');
Insert into cc_diritti values ('7s','Uso proprietà superficiaria');
Insert into cc_diritti values ('80','Usufrutto');
Insert into cc_diritti values ('8a','Usufrutto con diritto di accrescimento');
Insert into cc_diritti values ('8e','Usufrutto su enfiteusi');
Insert into cc_diritti values ('8s','Usufrutto su proprietà superficiaria');
Insert into cc_diritti values ('8 ','Comproprietario per l`area');
Insert into cc_diritti values ('90','Servitù');
Insert into cc_diritti values ('100','Oneri');
Insert into cc_diritti values ('12 ','Concedente in parte');
Insert into cc_diritti values ('14 ','Livellario parziale per');
Insert into cc_diritti values ('15 ','Usufruttuario parziale per');
Insert into cc_diritti values ('20 ','Livellario');
Insert into cc_diritti values ('21 ','Livellario per');
Insert into cc_diritti values ('22 ','Livellario in parte');
Insert into cc_diritti values ('25 ','Enfiteuta in parte');
Insert into cc_diritti values ('26 ','Colono perpetuo');
Insert into cc_diritti values ('27 ','Colono perpetuo per');
Insert into cc_diritti values ('28 ','Colono perpetuo in parte');
Insert into cc_diritti values ('30 ','Usufruttuario parziale');
Insert into cc_diritti values ('33 ','Cousufruttuario generale');
Insert into cc_diritti values ('36 ','Usufruttuario generale di livello');
Insert into cc_diritti values ('37 ','Usufruttuario parziale di livello');
Insert into cc_diritti values ('39 ','Usufruttuario parziale di enfiteusi');
Insert into cc_diritti values ('40 ','Usufruttuario generale di colonia');
Insert into cc_diritti values ('41 ','Usufruttuario parziale di colonia');
Insert into cc_diritti values ('42 ','Usufruttuario generale di dominio diretto');
Insert into cc_diritti values ('43 ','Usufruttuario parziale di dominio diretto');
Insert into cc_diritti values ('50 ','Cousufruttuario per');
Insert into cc_diritti values ('52 ','Usuario perpetuo');
Insert into cc_diritti values ('53 ','Usuario a tempo determinato');
Insert into cc_diritti values ('60 ','Cousufruttuario di livello');
Insert into cc_diritti values ('61 ','Cousufruttuario generale di livello');
Insert into cc_diritti values ('62 ','Usufruttuario di livello di');
Insert into cc_diritti values ('64 ','Comproprietario per parte di');
Insert into cc_diritti values ('70 ','Usufruttuario di colonia per');
Insert into cc_diritti values ('71 ','Usufruttuario di dominio diretto per');
Insert into cc_diritti values ('72 ','Cousufruttuario generale con diritto di accrescimento');
Insert into cc_diritti values ('16 ','Utilista della superficie');
Insert into cc_diritti values ('17 ','Utilista della superficie per');
Insert into cc_diritti values ('35 ','Beneficiario');
Insert into cc_diritti values ('65 ','Beneficiario per');
Insert into cc_diritti values ('54 ','Beneficiario di dominio diretto');
Insert into cc_diritti values ('46 ','Possessore');
Insert into cc_diritti values ('47 ','Possessore per');
Insert into cc_diritti values ('48 ','Compossessore');
Insert into cc_diritti values ('49 ','Compossessore per');
Insert into cc_diritti values ('55 ','Contestatario');
Insert into cc_diritti values ('56 ','Contestatario per');
Insert into cc_diritti values ('57 ','Contestatario per usufrutto');
Insert into cc_diritti values ('99 ','Presenza di titolo non codificato');
Insert into cc_diritti values ('990','Presenza di titolo non codificato');
Insert into cc_diritti values ('0 ','Assenza di titolo');
