--liquibase formatted sql
--changeset dmarotta:20250326_152438_cc_qualita_ins stripComments:false
--validCheckSum: 1:any

insert into cc_qualita values (1, 'seminativo');
insert into cc_qualita values (2, 'semin irrig');
insert into cc_qualita values (3, 'semin arbor');
insert into cc_qualita values (4, 'sem arb irr');
insert into cc_qualita values (5, 'sem irr arb');
insert into cc_qualita values (6, 'sem pez fos');
insert into cc_qualita values (7, 'sem arb p f');
insert into cc_qualita values (8, 'prato');
insert into cc_qualita values (9, 'prato irrig');
insert into cc_qualita values (10, 'prato arbor');
insert into cc_qualita values (11, 'prato ir ar');
insert into cc_qualita values (12, 'prato marc');
insert into cc_qualita values (13, 'prato mar ar');
insert into cc_qualita values (14, 'marcita');
insert into cc_qualita values (15, 'risaia');
insert into cc_qualita values (16, 'risaia stab');
insert into cc_qualita values (17, 'orto');
insert into cc_qualita values (18, 'orto irrig');
insert into cc_qualita values (19, 'orto arbor');
insert into cc_qualita values (20, 'orto ar irr');
insert into cc_qualita values (21, 'orto frutt');
insert into cc_qualita values (22, 'orto pez fos');
insert into cc_qualita values (23, 'orto fiori');
insert into cc_qualita values (24, 'orto ir fi');
insert into cc_qualita values (25, 'ort viv flo');
insert into cc_qualita values (26, 'vivaio');
insert into cc_qualita values (27, 'viv orn fl');
insert into cc_qualita values (28, 'giardini');
insert into cc_qualita values (29, 'vigneto');
insert into cc_qualita values (30, 'vigneto arb');
insert into cc_qualita values (31, 'vigneto irr');
insert into cc_qualita values (32, 'vig uva tav');
insert into cc_qualita values (33, 'vign frutt');
insert into cc_qualita values (34, 'vign ulivet');
insert into cc_qualita values (35, 'vign mandor');
insert into cc_qualita values (36, 'uliveto');
insert into cc_qualita values (37, 'uliv agrum');
insert into cc_qualita values (38, 'uliv fichet');
insert into cc_qualita values (39, 'ul fich man');
insert into cc_qualita values (40, 'uliv frass');
insert into cc_qualita values (41, 'uliv frutt');
insert into cc_qualita values (42, 'uliv sommac');
insert into cc_qualita values (43, 'uliv vignet');
insert into cc_qualita values (44, 'uliv sugher');
insert into cc_qualita values (45, 'uliv mandor');
insert into cc_qualita values (46, 'ul man pist');
insert into cc_qualita values (47, 'frutteto');
insert into cc_qualita values (48, 'frutt irrig');
insert into cc_qualita values (49, 'agrumeto');
insert into cc_qualita values (50, 'agrum aranc');
insert into cc_qualita values (51, 'agrum irrig');
insert into cc_qualita values (52, 'agrum uliv');
insert into cc_qualita values (53, 'alpe');
insert into cc_qualita values (54, 'aranceto');
insert into cc_qualita values (55, 'canneto');
insert into cc_qualita values (56, 'cappereto');
insert into cc_qualita values (57, 'carrubeto');
insert into cc_qualita values (58, 'castagneto');
insert into cc_qualita values (59, 'cast frutto');
insert into cc_qualita values (60, 'cast frass');
insert into cc_qualita values (61, 'chiusa');
insert into cc_qualita values (62, 'eucalipteto');
insert into cc_qualita values (63, 'ficheto');
insert into cc_qualita values (64, 'fico india');
insert into cc_qualita values (65, 'fico mandor');
insert into cc_qualita values (66, 'frassineto');
insert into cc_qualita values (67, 'gelseto');
insert into cc_qualita values (68, 'limoneto');
insert into cc_qualita values (69, 'mandorleto');
insert into cc_qualita values (70, 'mandor fich');
insert into cc_qualita values (71, 'mandor fico');
insert into cc_qualita values (72, 'mandarineto');
insert into cc_qualita values (73, 'noceto');
insert into cc_qualita values (74, 'noccioleto');
insert into cc_qualita values (75, 'nocc vignet');
insert into cc_qualita values (76, 'palmeto');
insert into cc_qualita values (77, 'pescheto');
insert into cc_qualita values (78, 'pioppeto');
insert into cc_qualita values (79, 'pistacch');
insert into cc_qualita values (80, 'pometo');
insert into cc_qualita values (81, 'querceto');
insert into cc_qualita values (82, 'querc ghian');
insert into cc_qualita values (83, 'roseto');
insert into cc_qualita values (84, 'saliceto');
insert into cc_qualita values (85, 'salceto');
insert into cc_qualita values (86, 'sommaccheto');
insert into cc_qualita values (87, 'sommac arb');
insert into cc_qualita values (88, 'somm mandor');
insert into cc_qualita values (89, 'sommac uliv');
insert into cc_qualita values (90, 'sughereto');
insert into cc_qualita values (91, 'pascolo');
insert into cc_qualita values (92, 'pascolo arb');
insert into cc_qualita values (93, 'pasc cespug');
insert into cc_qualita values (94, 'pascolo bc');
insert into cc_qualita values (95, 'pascolo bm');
insert into cc_qualita values (96, 'pascolo ba');
insert into cc_qualita values (97, 'bosco ceduo');
insert into cc_qualita values (98, 'bosco misto');
insert into cc_qualita values (99, 'bosco alto');
insert into cc_qualita values (100, 'palud spart');
insert into cc_qualita values (101, 'incolt prod');
insert into cc_qualita values (102, 'orto irr ar');
insert into cc_qualita values (103, 'nocciol irr');
insert into cc_qualita values (104, 'sem car irr');
insert into cc_qualita values (105, 'pereto');
insert into cc_qualita values (106, 'sem irr prot');
insert into cc_qualita values (107, 'bosco rap ac');
insert into cc_qualita values (126, 'serra');
insert into cc_qualita values (127, 'funghicoltur');
insert into cc_qualita values (130, 'arativi');
insert into cc_qualita values (131, 'seminativi');
insert into cc_qualita values (132, 'prati');
insert into cc_qualita values (133, 'orti');
insert into cc_qualita values (134, 'vigneti');
insert into cc_qualita values (135, 'pascoli');
insert into cc_qualita values (136, 'alpi');
insert into cc_qualita values (137, 'lag pal st');
insert into cc_qualita values (138, 'boschi');
insert into cc_qualita values (150, 'incolt ster');
insert into cc_qualita values (151, 'lago pubbl');
insert into cc_qualita values (152, 'laguna');
insert into cc_qualita values (153, 'stagno');
insert into cc_qualita values (180, 'cava');
insert into cc_qualita values (181, 'lago pesca');
insert into cc_qualita values (182, 'miniera');
insert into cc_qualita values (183, 'salina');
insert into cc_qualita values (184, 'stagn pesca');
insert into cc_qualita values (185, 'tonnara');
insert into cc_qualita values (186, 'torbiera');
insert into cc_qualita values (187, 'valle pesca');
insert into cc_qualita values (188, 'acque priv');
insert into cc_qualita values (200, 'aeroporto d');
insert into cc_qualita values (201, 'aer fort d');
insert into cc_qualita values (202, 'autovia sp');
insert into cc_qualita values (203, 'area dem pp');
insert into cc_qualita values (204, 'banchina');
insert into cc_qualita values (205, 'cimitero');
insert into cc_qualita values (206, 'ferrovia sp');
insert into cc_qualita values (207, 'fortificaz');
insert into cc_qualita values (208, 'giard pub');
insert into cc_qualita values (209, 'giard dem');
insert into cc_qualita values (210, 'giard com');
insert into cc_qualita values (211, 'giard prov');
insert into cc_qualita values (212, 'molo');
insert into cc_qualita values (213, 'parco pubb');
insert into cc_qualita values (214, 'parco deman');
insert into cc_qualita values (215, 'parco comun');
insert into cc_qualita values (216, 'parco prov');
insert into cc_qualita values (217, 'p v rimembr');
insert into cc_qualita values (218, 'pza d armi');
insert into cc_qualita values (219, 'porto');
insert into cc_qualita values (220, 'somm arg 2');
insert into cc_qualita values (221, 'somm arg 3');
insert into cc_qualita values (222, 'tranvia sp');
insert into cc_qualita values (223, 'somm arg 1');
insert into cc_qualita values (250, 'canale bon');
insert into cc_qualita values (251, 'canale irr');
insert into cc_qualita values (252, 'gora');
insert into cc_qualita values (270, 'antichita');
insert into cc_qualita values (271, 'area fab dm');
insert into cc_qualita values (272, 'area promis');
insert into cc_qualita values (273, 'area rurale');
insert into cc_qualita values (274, 'area urbana');
insert into cc_qualita values (275, 'corte urban');
insert into cc_qualita values (276, 'costr no ab');
insert into cc_qualita values (277, 'fa div sub');
insert into cc_qualita values (278, 'fabb promis');
insert into cc_qualita values (279, 'fabb rurale');
insert into cc_qualita values (280, 'fabb diruto');
insert into cc_qualita values (281, 'fr div sub');
insert into cc_qualita values (282, 'ente urbano');
insert into cc_qualita values (283, 'fu d accert');
insert into cc_qualita values (284, 'porz acc fr');
insert into cc_qualita values (285, 'porz acc fu');
insert into cc_qualita values (286, 'porz di fa');
insert into cc_qualita values (287, 'porz di fr');
insert into cc_qualita values (288, 'porz rur fp');
insert into cc_qualita values (290, 'porz di fu');
insert into cc_qualita values (300, 'acque esent');
insert into cc_qualita values (301, 'piazza pubb');
insert into cc_qualita values (302, 'strade pubb');
insert into cc_qualita values (350, 'accesso');
insert into cc_qualita values (351, 'accessorio');
insert into cc_qualita values (352, 'aia');
insert into cc_qualita values (353, 'andito');
insert into cc_qualita values (354, 'androne');
insert into cc_qualita values (355, 'area');
insert into cc_qualita values (356, 'ascensore');
insert into cc_qualita values (357, 'autorimessa');
insert into cc_qualita values (358, 'ballatoio');
insert into cc_qualita values (359, 'bindolo');
insert into cc_qualita values (360, 'bottino');
insert into cc_qualita values (361, 'bucataio');
insert into cc_qualita values (362, 'canale priv');
insert into cc_qualita values (363, 'cantina');
insert into cc_qualita values (364, 'capanna');
insert into cc_qualita values (365, 'cappella');
insert into cc_qualita values (366, 'carbonile');
insert into cc_qualita values (367, 'casello');
insert into cc_qualita values (368, 'casotto');
insert into cc_qualita values (369, 'cisterna');
insert into cc_qualita values (370, 'concimaia');
insert into cc_qualita values (371, 'conigliera');
insert into cc_qualita values (372, 'corridoio');
insert into cc_qualita values (373, 'corte');
insert into cc_qualita values (374, 'fontana');
insert into cc_qualita values (375, 'fontanile');
insert into cc_qualita values (376, 'forno');
insert into cc_qualita values (377, 'frantoio');
insert into cc_qualita values (378, 'garage');
insert into cc_qualita values (379, 'garitta');
insert into cc_qualita values (380, 'grotta');
insert into cc_qualita values (381, 'ingresso');
insert into cc_qualita values (382, 'latrina');
insert into cc_qualita values (383, 'lavanderia');
insert into cc_qualita values (384, 'lavatoio');
insert into cc_qualita values (385, 'legnaia');
insert into cc_qualita values (386, 'locale dep');
insert into cc_qualita values (387, 'loggia');
insert into cc_qualita values (388, 'luogo dep');
insert into cc_qualita values (389, 'macero');
insert into cc_qualita values (390, 'montacarichi');
insert into cc_qualita values (391, 'muro');
insert into cc_qualita values (392, 'noria');
insert into cc_qualita values (393, 'oratorio');
insert into cc_qualita values (394, 'palmeto');
insert into cc_qualita values (395, 'passaggio');
insert into cc_qualita values (396, 'passo');
insert into cc_qualita values (397, 'piazza');
insert into cc_qualita values (398, 'piazzale');
insert into cc_qualita values (399, 'pollaio');
insert into cc_qualita values (400, 'pompa');
insert into cc_qualita values (401, 'porcile');
insert into cc_qualita values (402, 'portico');
insert into cc_qualita values (403, 'portineria');
insert into cc_qualita values (404, 'portone');
insert into cc_qualita values (405, 'pozzo');
insert into cc_qualita values (406, 'resede');
insert into cc_qualita values (407, 'rifugio ant');
insert into cc_qualita values (408, 'rimessa');
insert into cc_qualita values (409, 'ripostiglio');
insert into cc_qualita values (410, 'scala');
insert into cc_qualita values (411, 'scolo acqua');
insert into cc_qualita values (412, 'seccatoio');
insert into cc_qualita values (413, 'sedime');
insert into cc_qualita values (414, 'sentina');
insert into cc_qualita values (415, 'sorgiva');
insert into cc_qualita values (416, 'sottoscala');
insert into cc_qualita values (417, 'sottopassag');
insert into cc_qualita values (418, 'spazio');
insert into cc_qualita values (419, 'stalla');
insert into cc_qualita values (420, 'strada priv');
insert into cc_qualita values (421, 'terrazzo');
insert into cc_qualita values (422, 'tettoia');
insert into cc_qualita values (423, 'tinaia');
insert into cc_qualita values (424, 'vano');
insert into cc_qualita values (425, 'vasca');
insert into cc_qualita values (450, 'rel ente ur');
insert into cc_qualita values (451, 'rel acc com');
insert into cc_qualita values (452, 'rel f d sub');
insert into cc_qualita values (453, 'rel acq es');
insert into cc_qualita values (454, 'relit strad');
insert into cc_qualita values (455, 'terr n form');
insert into cc_qualita values (500, 'casa e corte');
insert into cc_qualita values (501, 'fabb e corte');
insert into cc_qualita values (504, 'incolto');
insert into cc_qualita values (505, 'improdutt');
insert into cc_qualita values (506, 'sentiero');
insert into cc_qualita values (507, 'ponte');
insert into cc_qualita values (508, 'cavalcavia');
insert into cc_qualita values (509, 'casa stalla');
insert into cc_qualita values (510, 'chiesa');
insert into cc_qualita values (511, 'edificabile');
insert into cc_qualita values (512, 'cortile');
insert into cc_qualita values (513, 'magazzino');
insert into cc_qualita values (514, 'fosso');
insert into cc_qualita values (515, 'casa');
insert into cc_qualita values (516, 'edificio');
insert into cc_qualita values (517, 'fabbricato');
insert into cc_qualita values (602, 'lag pal sta');
insert into cc_qualita values (993, 'modello 26');
insert into cc_qualita values (997, 'sop var ter');
insert into cc_qualita values (998, 'soppresso');
insert into cc_qualita values (999, 'disponibile');
