--liquibase formatted sql
--changeset dmarotta:20250326_152438_cotr_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE codici_tributo DISABLE ALL TRIGGERS;

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8700, 'CANONE UNICO PROVV. MANCA CODICE COATTIVO', null, 'CUNI', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8701, 'SANZIONI CANONE UNICO PROVV. MANCA CODICE COATTIVO', null, 'CUNI', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8702, 'INTERESSI CANONE UNICO PROVV. MANCA CODICE COATTIVO', null, 'CUNI', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8703, 'SPESE DI NOTIFICA CANONE UNICO PROVV. MANCA CODICE COATTIVO', null, 'CUNI', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8600, 'CANONE UNICO - PUBBICITA''', 'PUBBLICITA''', 'CUNI', 111111, 'CUNI', null, null, null, null, '111111', 'ICP');

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8660, 'CANONE UNICO - OCCUPAZIONE', 'OCCUPAZIONE', 'CUNI', 111111, 'CUNI', null, null, null, null, '111111', 'TOSAP');

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8610, 'CANONE UNICO - AFFISSIONI', 'AFFISSIONI', 'CUNI', 111111, 'CUNI', null, null, null, null, '111111', 'ICP');

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8670, 'CANONE UNICO - MERCATI', 'MERCATI', 'CUNI', 222222, 'CUME', null, null, null, null, '222222', 'TOSAP');

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (411, 'IMPOSTA COMUNALE IMPRESE ARTI E PROFESSIONI', 'I.C.I.A.P.', 'ICIAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (412, 'SOPRATTASSA PER OMESSA O TARDIVA PRES. DENUNCIA', 'SOPRATTASSA OMESSA TARDIVA DENUNCIA', 'ICIAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (413, 'SOPRATTASSA PER INFEDELE O INESATTA DENUNCIA', 'SOPRATTASSA INFEDELE INESATTA DENUNCIA', 'ICIAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (414, 'SOPRATTASSA PER OMESSO,PARZ. O TARDIVO VERSAMENTO', 'OMESSO PARZIALE TARDIVO VERSAMENTO', 'ICIAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (415, 'PENE PECUNIARIE - I.C.I.A.P.', 'PENE PECUNIARIE I.C.I.A.P.', 'ICIAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (416, 'INTERESSI MORATORI - I.C.I.A.P.', 'INTERESSI MORATORI I.C.I.A.P.', 'ICIAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (423, 'SOPRATTASSE (LEGGE 507)', 'SOPRATTASSE  ART. 76 LEGGE 507', 'TARSU', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (424, 'INTERESSI PER RITARDATA ISCRIZIONE (TRIBUTO)', 'INTERESSI PER RITARDATA ISCRIZIONE (TRIBUTO)', 'TARSU', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (433, 'T.A.R.S.U. PER LE ATTIVITA''', 'TARSU ATTIVITA''', 'TARSU', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (434, 'TASSA RACCOLTA E SMALTIMENTO RIFIUTI SOLIDI URBANI', 'TASSA RACCOLTA RIFIUTI', 'TARSU', null, null, null, 'S', null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (453, 'TASSA OCCUPAZIONE SPAZI ED AREE PUBBLICHE', 'T.O.S.A.P.', 'TOSAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8500, 'PUBBLICITA''', 'PUBBLICITA''', 'ICP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8501, 'PUBBLICITA'' A RUOLO', 'PUBBLICITA'' A RUOLO', 'ICP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8523, 'TOSAP TEMPORANEA', 'tosap   ', 'TOSAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8560, 'T.O.S.A.P.', 'T.O.S.A.P.   ', 'TOSAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8561, 'SOPRATTASSE T.O.S.A.P.', 'SOPRATTASSE T.O.S.A.P.', 'TOSAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8562, 'INTERESSI T.O.S.A.P.', 'INTERESSI T.O.S.A.P.', 'TOSAP', null, null, null, null, null, null, null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8858, 'IMPOSTA MUNICIPALE UNICA', 'IMU', 'ICI', null, null, null, null, null, '2R60', null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8859, 'IMPOSTA MUNICIPALE UNICA - SANZIONI', 'IMPOSTA MUNICIPALE UNICA - SANZIONI', 'ICI', null, null, null, null, null, '2R62', null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8861, 'IMPOSTA MUNICIPALE UNICA - INTERESSI', 'IMPOSTA MUNICIPALE UNICA - INTERESSI', 'ICI', null, null, null, null, null, '2R61', null, null);

insert into codici_tributo (TRIBUTO, DESCRIZIONE, DESCRIZIONE_RUOLO, TIPO_TRIBUTO, CONTO_CORRENTE, DESCRIZIONE_CC, FLAG_STAMPA_CC, FLAG_RUOLO, FLAG_CALCOLO_INTERESSI, COD_ENTRATA, GRUPPO_TRIBUTO, TIPO_TRIBUTO_PREC)
values (8874, 'IMPOSTA MUNICIPALE UNICA - SPESE', 'IMPOSTA MUNICIPALE UNICA - SPESE', 'ICI', null, null, null, null, null, '2R63', null, null);

ALTER TABLE codici_tributo ENABLE ALL TRIGGERS;
