--liquibase formatted sql
--changeset dmarotta:20250326_152438_expe_ins stripComments:false
--validCheckSum: 1:any


ALTER TABLE export_personalizzati DISABLE ALL TRIGGERS;

INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (15,'050029','Pontedera - Estrazione TARES (Poste) (Pontedera)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (15,'037006','Bologna - Estrazione TARES (Poste) (Pontedera)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (16,'037006','Bologna - Estrazione COSAP con F24');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (17,'037006','Bologna - Estrazione ICP con F24');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (101,'091065','Oliena (Siscotel) - Estrazione ICI (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (101,'037006','Bologna - Estrazione ICI (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (102,'048010','Castelfiorentino - Versamenti ICP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (102,'048006','Comacchio - Versamenti ICP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (102,'037006','Bologna - Versamenti ICP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (103,'025006','Belluno - Dichiarazioni ANCI Attive');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (103,'037006','Bologna - Dichiarazioni ANCI Attive');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (104,'028032','Cittadella - Estrazione ICI: Anagrafica');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (104,'037006','Bologna - Estrazione ICI: Anagrafica');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (105,'028032','Cittadella - Estrazione ICI: Immobili');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (105,'037006','Bologna - Estrazione ICI: Immobili');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (106,'015175','Pioltello - Bollettazione ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (106,'037006','Bologna - Bollettazione ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (107,'015175','Pioltello - Bollettazione TARSU: Contribuenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (107,'037006','Bologna - Bollettazione TARSU: Contribuenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (108,'015175','Pioltello - Bollettazione TARSU: Oggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (108,'037006','Bologna - Bollettazione TARSU: Oggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (109,'048022','Impruneta - Versamenti COSAP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (109,'050029','Pontedera - Versamenti COSAP (Poste) (da eliminare)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (109,'048033','Pontassieve - Versamenti COSAP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (109,'048010','Castelfiorentino - Versamenti COSAP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (109,'037006','Bologna - Versamenti COSAP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (110,'037058','Savigno - Trasmissione MAV');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (110,'037006','Bologna - Trasmissione MAV');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (111,'015034','Brugherio - Estrazione TARSU GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (111,'108012','Brugherio - Estrazione TARSU GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (111,'015175','Pioltello - Estrazione TARSU GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (111,'037006','Bologna - Estrazione TARSU GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (112,'015175','Pioltello - Estrazione ICI GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (112,'037006','Bologna - Estrazione ICI GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (113,'015175','Pioltello - Estrazione Versamenti ICI GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (113,'037006','Bologna - Estrazione Versamenti ICI GIT');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (114,'037006','Bologna - Abilitati Web Non Contribuenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (114,'035012','Casalgrande - Abilitati Web Non Contribuenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (151,'001219','Rivoli - ELIFIS Anagrafica dei Soggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (151,'050029','Pontedera - ELIFIS Anagrafica dei Soggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (151,'037006','Bologna - ELIFIS Anagrafica dei Soggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (152,'001219','Rivoli - ELIFIS Anagrafica degli Oggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (152,'050029','Pontedera - ELIFIS Anagrafica degli Oggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (152,'037006','Bologna - ELIFIS Anagrafica degli Oggetti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (153,'001219','Rivoli - ELIFIS Comuni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (153,'050029','Pontedera - ELIFIS Comuni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (153,'037006','Bologna - ELIFIS Comuni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (154,'001219','Rivoli - ELIFIS Nazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (154,'050029','Pontedera - ELIFIS Nazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (154,'037006','Bologna - ELIFIS Nazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (155,'001219','Rivoli - ELIFIS Strade');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (155,'050029','Pontedera - ELIFIS Strade');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (155,'037006','Bologna - ELIFIS Strade');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (156,'001219','Rivoli - ELIFIS Civici');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (156,'050029','Pontedera - ELIFIS Civici');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (156,'037006','Bologna - ELIFIS Civici');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (157,'001219','Rivoli - ELIFIS Denunce ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (157,'050029','Pontedera - ELIFIS Denunce ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (157,'037006','Bologna - ELIFIS Denunce ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (158,'001219','Rivoli - ELIFIS Aliquote Speciali ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (158,'050029','Pontedera - ELIFIS Aliquote Speciali ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (158,'037006','Bologna - ELIFIS Aliquote Speciali ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (159,'001219','Rivoli - ELIFIS Detrazioni ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (159,'050029','Pontedera - ELIFIS Detrazioni ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (159,'037006','Bologna - ELIFIS Detrazioni ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (160,'001219','Rivoli - ELIFIS Versamenti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (160,'050029','Pontedera - ELIFIS Versamenti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (160,'037006','Bologna - ELIFIS Versamenti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (161,'001219','Rivoli - ELIFIS Provvedimenti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (161,'050029','Pontedera - ELIFIS Provvedimenti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (161,'037006','Bologna - ELIFIS Provvedimenti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (162,'001219','Rivoli - ELIFIS Dovuti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (162,'050029','Pontedera - ELIFIS Dovuti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (162,'037006','Bologna - ELIFIS Dovuti ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (163,'001219','Rivoli - ELIFIS Aliquote ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (163,'050029','Pontedera - ELIFIS Aliquote ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (163,'037006','Bologna - ELIFIS Aliquote ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (164,'001219','Rivoli - ELIFIS Agevolazioni ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (164,'050029','Pontedera - ELIFIS Agevolazioni ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (164,'037006','Bologna - ELIFIS Agevolazioni ICI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (165,'001219','Rivoli - ELIFIS Denunce RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (165,'050029','Pontedera - ELIFIS Denunce RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (165,'037006','Bologna - ELIFIS Denunce RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (166,'001219','Rivoli - ELIFIS Provvedimenti RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (166,'050029','Pontedera - ELIFIS Provvedimenti RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (166,'037006','Bologna - ELIFIS Provvedimenti RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (167,'001219','Rivoli - ELIFIS Classe Tariffa RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (167,'050029','Pontedera - ELIFIS Classe Tariffa RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (167,'037006','Bologna - ELIFIS Classe Tariffa RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (168,'001219','Rivoli - ELIFIS Tipi Oggetto RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (168,'050029','Pontedera - ELIFIS Tipi Oggetto RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (168,'037006','Bologna - ELIFIS Tipi Oggetto RSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (201,'025006','Belluno - Bollettini ICI Completi (Bel)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (201,'037006','Bologna - Bollettini ICI Completi (Bel)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (211,'017025','Bovezzo - Bollettini ICI in bianco (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (211,'037006','Bologna - Bollettini ICI in bianco (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (212,'017025','Bovezzo - Bollettini ICI completi (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (212,'037006','Bologna - Bollettini ICI completi (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (213,'017025','Bovezzo - Trasmissione Fatture TIA RID (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (213,'037006','Bologna - Trasmissione Fatture TIA RID (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (214,'017025','Bovezzo - Trasmissione RID (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (214,'037006','Bologna - Trasmissione RID (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (215,'017025','Bovezzo - Trasmissione Fatture TIA MAV (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (215,'037006','Bologna - Trasmissione Fatture TIA MAV (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (216,'017025','Bovezzo - Trasmissione MAV (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (216,'037006','Bologna - Trasmissione MAV (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (217,'017025','Bovezzo - Bollettini TASI in bianco (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (217,'037006','Bologna - Bollettini TASI in bianco (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (218,'017025','Bovezzo - Bollettini TASI completi (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (218,'037006','Bologna - Bollettini TASI completi (Bov)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (221,'035012','Casalgrande - Bollettini ICI Completi (Cas)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (221,'037006','Bologna - Bollettini ICI Completi (Cas)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (231,'049011','Marciana Marina - Versamenti COSAP (Poste) (Marc)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (231,'037006','Bologna - Versamenti COSAP (Poste) (Marc)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (241,'015175','Pioltello - Trasmissione MAV (Pio)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (241,'037006','Bologna - Trasmissione MAV (Pio)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (251,'048033','Pontassieve - Dati TARSU: Anagrafe  (Pon)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (251,'037006','Bologna - Dati TARSU: Anagrafe  (Pon)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (252,'048033','Pontassieve - Dati TARSU: Archivio Comuni (Pon)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (252,'037006','Bologna - Dati TARSU: Archivio Comuni (Pon)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (253,'048033','Pontassieve - Dati TARSU: Archivio Vie (Pon)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (253,'037006','Bologna - Dati TARSU: Archivio Vie (Pon)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (261,'012096','Malnate (Siscotel) - Anagrafe TARSU (Mal)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (261,'037006','Bologna - Anagrafe TARSU (Mal)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (262,'012096','Malnate (Siscotel) - Domicili TARSU (Mal)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (262,'037006','Bologna - Domicili TARSU (Mal)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (263,'012096','Malnate (Siscotel) - Beni TARSU (Mal)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (263,'037006','Bologna - Beni TARSU (Mal)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (271,'012127','Tradate (Siscotel) - Trasmissione MAV (Tra)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (271,'037006','Bologna - Trasmissione MAV (Tra)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (272,'012127','Tradate (Siscotel) - Trasmissione Fatture TIA (Seprio)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (272,'037006','Bologna - Trasmissione Fatture TIA (Seprio)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (281,'034037','Sorbolo - TARSU ENIA: Utenze TARSU/TIA (Sor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (281,'037006','Bologna - TARSU ENIA: Utenze TARSU/TIA (Sor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (282,'034037','Sorbolo - TARSU ENIA: Archivio Categorie (Sor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (282,'037006','Bologna - TARSU ENIA: Archivio Categorie (Sor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (291,'018167','Valeggio - Conferitori (Val)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (291,'037006','Bologna - Conferitori (Val)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (301,'015093','Corsico - Trasmissione COSAP MAV (Cor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (301,'037006','Bologna - Trasmissione COSAP MAV (Cor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (302,'015093','Corsico - Trasmissione Violazioni ICI MAV (Cor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (302,'037006','Bologna - Trasmissione Violazioni ICI MAV (Cor)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (311,'108027','Limbiate - Trasmissione TARSU MAV (Lim)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (311,'037006','Bologna - Trasmissione TARSU MAV (Lim)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (312,'037006','Bologna - Trasmissione TARSU RID');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (312,'108027','Limbiate - Trasmissione TARSU RID');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (321,'037054','San Lazzaro di Savena - Trasmissione TARSU MAV (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (321,'037006','Bologna - Trasmissione TARSU MAV (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (322,'037054','San Lazzaro di Savena - Trasmissione TARSU RID su MAV (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (322,'037006','Bologna - Trasmissione TARSU RID su MAV (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (323,'037054','San Lazzaro di Savena - Estrazione Ecototem (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (323,'037006','Bologna - Estrazione Ecototem (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (324,'037054','San Lazzaro di Savena - Trasmissione TARSU RID (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (324,'037006','Bologna - Trasmissione TARSU RID (SLS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (331,'051033','San Giovanni Valdarno - Trasmissione TARSU MAV (SGV)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (331,'037006','Bologna - Trasmissione TARSU MAV (SGV)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (341,'016003','Albano Sant Alessandro - Estrazione TARSU maggiorenni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (341,'037006','Bologna - Estrazione TARSU maggiorenni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (351,'095019','Cuglieri - Trasmissione TARSU Unione Comuni (SIS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (351,'037006','Bologna - Trasmissione TARSU Unione Comuni (SIS)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (352,'025006','Belluno - Estrazione F24 TASI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (352,'037054','San Lazzaro di Savena - Estrazione F24 TASI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (352,'037006','Bologna - Estrazione F24 TASI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (353,'037006','Bologna - Estrazione TARSU Engineering');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (353,'037054','San Lazzaro di Savena - Estrazione TARSU Engineering');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'050029','Pontedera - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'015192','San Donato Milanese - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'051033','San Giovanni Valdarno - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'052028','San Gimignano - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'015175','Pioltello - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'015093','Corsico - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'037006','Bologna - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'048033','Pontassieve - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'053021','Roccastrada - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (354,'107004','Carloforte - Estrazione Accertamenti Automatici TARSU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (361,'037054','San Lazzaro di Savena - ENG Tariffe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (361,'037006','Bologna - ENG Tariffe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (362,'037054','San Lazzaro di Savena - ENG Anagrafe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (362,'037006','Bologna - ENG Anagrafe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (363,'037054','San Lazzaro di Savena - ENG Utenze');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (363,'037006','Bologna - ENG Utenze');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (364,'037054','San Lazzaro di Savena - ENG Provvedimenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (364,'037006','Bologna - ENG Provvedimenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (365,'037054','San Lazzaro di Savena - ENG Versamenti Omessi');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (365,'037006','Bologna - ENG Versamenti Omessi');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (366,'037054','San Lazzaro di Savena - ENG Versamenti Parziali');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (366,'037006','Bologna - ENG Versamenti Parziali');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (367,'037054','San Lazzaro di Savena - Estrazione Accertamenti TARES/TIA/TARI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (367,'037006','Bologna - Estrazione Accertamenti TARES/TIA/TARI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (371,'037006','Bologna - STD Comuni Esteri');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (371,'037054','San Lazzaro di Savena - STD Comuni Esteri');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (371,'025006','Belluno - STD Comuni Esteri');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (372,'037006','Bologna - STD Stradario');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (372,'037054','San Lazzaro di Savena - STD Stradario');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (372,'025006','Belluno - STD Stradario');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (373,'037006','Bologna - STD Anagrafe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (373,'037054','San Lazzaro di Savena - STD Anagrafe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (373,'025006','Belluno - STD Anagrafe');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (374,'037006','Bologna - STD Aliquote');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (374,'037054','San Lazzaro di Savena - STD Aliquote');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (375,'037006','Bologna - STD Categorie Catasto');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (375,'037054','San Lazzaro di Savena - STD Categorie Catasto');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (376,'037006','Bologna - STD Detrazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (376,'037054','San Lazzaro di Savena - STD Detrazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (377,'037006','Bologna - STD Fonti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (377,'037054','San Lazzaro di Savena - STD Fonti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (378,'037006','Bologna - STD Moltiplicatori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (378,'037054','San Lazzaro di Savena - STD Moltiplicatori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (379,'037006','Bologna - STD Motivi Detrazione');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (379,'037054','San Lazzaro di Savena - STD Motivi Detrazione');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (380,'037006','Bologna - STD Rivalutazioni Rendita');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (380,'037054','San Lazzaro di Savena - STD Rivalutazioni Rendita');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (381,'037006','Bologna - STD Tipi Aliquota');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (381,'037054','San Lazzaro di Savena - STD Tipi Aliquota');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (382,'037006','Bologna - STD Tipi Carica');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (382,'037054','San Lazzaro di Savena - STD Tipi Carica');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (383,'037006','Bologna - STD Tipi Stato');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (383,'037054','San Lazzaro di Savena - STD Tipi Stato');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (384,'037006','Bologna - STD Tipi Uso');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (384,'037054','San Lazzaro di Savena - STD Tipi Uso');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (385,'037006','Bologna - STD Tipi Utilizzo');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (385,'037054','San Lazzaro di Savena - STD Tipi Utilizzo');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (386,'037006','Bologna - STD Immobili');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (386,'037054','San Lazzaro di Savena - STD Immobili');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (387,'037006','Bologna - STD Riferimenti Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (387,'037054','San Lazzaro di Savena - STD Riferimenti Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (388,'037006','Bologna - STD Utilizzi Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (388,'037054','San Lazzaro di Savena - STD Utilizzi Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (389,'037006','Bologna - STD Denunce');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (389,'037054','San Lazzaro di Savena - STD Denunce');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (390,'037006','Bologna - STD Dettagli Denuncia');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (390,'037054','San Lazzaro di Savena - STD Dettagli Denuncia');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (391,'037006','Bologna - STD Aliquote Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (391,'037054','San Lazzaro di Savena - STD Aliquote Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (392,'037006','Bologna - STD Detrazioni Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (392,'037054','San Lazzaro di Savena - STD Detrazioni Immobile');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (393,'037054','San Lazzaro di Savena - STD Detrazioni Figli');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (393,'037006','Bologna - STD Detrazioni Figli');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (394,'037054','San Lazzaro di Savena - STD Maggiori Detrazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (394,'037006','Bologna - STD Maggiori Detrazioni');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (395,'037054','San Lazzaro di Savena - STD Provvedimenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (395,'037006','Bologna - STD Provvedimenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (396,'037054','San Lazzaro di Savena - STD Versamenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (396,'037006','Bologna - STD Versamenti');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (397,'037006','Bologna - STD Contatti Contribuente');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (397,'037054','San Lazzaro di Savena - STD Contatti Contribuente');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (398,'037006','Bologna - STD Sanzioni Provvedimento');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (398,'037054','San Lazzaro di Savena - STD Sanzioni Provvedimento');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (411,'025006','Belluno - Denunce (vers. Omnia)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (411,'037006','Bologna - Denunce (vers. Omnia)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (412,'025006','Belluno - Dettagli Denuncia (vers. Omnia)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (412,'037006','Bologna - Dettagli Denuncia (vers. Omnia)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (421,'037006','Bologna - Dovuto Versato TARSU per F24');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (421,'048033','Pontassieve - Dovuto Versato TARSU per F24');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (421,'015192','San Donato Milanese - Dovuto Versato TARSU per F24');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (422,'037006','Bologna - Estrazione COSAP');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (422,'015093','Corsico - Estrazione COSAP');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (423,'107004','Carloforte - Estrazione Liquidazioni IMU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (423,'037006','Bologna - Estrazione Liquidazioni IMU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (423,'015175','Pioltello - Estrazione Liquidazioni IMU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (423,'108009','Biassono - Estrazione Liquidazioni IMU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (424,'037006','Bologna - Versamenti COSAP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (424,'047014','Prov. di Pistoia - Versamenti COSAP (Poste)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (425,'037006','Bologna - GEOFOR: Estrazione file completo');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (425,'050029','Pontedera - GEOFOR: Estrazione file completo');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (426,'107004','Carloforte - Estrazione Liquidazioni IMU');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (426,'037006','Bologna - Estrazione Liquidazioni TASI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (426,'015175','Pioltello - Estrazione Liquidazioni TASI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (427,'048033','Pontassieve - Estrazione TARI Garbage');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (427,'048035','Reggello - Estrazione TARI Garbage');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (427,'037006','Bologna - Estrazione TARI Garbage');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (428,'037006','Bologna - Trasmissione TARI RID');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (428,'036013','Fiorano Modenese - Trasmissione TARI RID');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (429,'012083','Induno Olona - Trasmissione TARI ASPEM');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (429,'037006','Bologna - Trasmissione TARI ASPEM');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (430,'037006','Bologna - Estrazione Utenze TARI (S.Gimignano/Roccastrada)');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (430,'052028','San Gimignano - Estrazione Utenze TARI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (430,'053021','Roccastrada - Estrazione Utenze TARI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (431,'037006','Bologna - Estrazione TARI per ASPEM');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (431,'040046','Sogliano al Rubicone  - Estrazione Ruolo TARI');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (432,'037006','Bologna - Estrazione Utenze TARI per ECUOSACCO');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (432,'108012','Brugherio  - Estrazione Utenze TARI per ECUOSACCO');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (441,'037006','Bologna - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (441,'023089','Valeggio sul Mincio  - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (441,'108009','Biassono - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (442,'037006','Bologna - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (442,'023089','Valeggio sul Mincio  - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (442,'108009','Biassono - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (443,'037006','Bologna - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (443,'023089','Valeggio sul Mincio  - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (443,'108009','Biassono - Estrazione Ruolo TARI per Solori');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (444,'015192','San Donato Milanese - Estrazione Utenze TARI per Accesso Isola Ecologica');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (444,'108009','Biassono - Estrazione Utenze TARI per Accesso Isola Ecologica');
INSERT INTO export_personalizzati ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) VALUES (444,'037006','Bologna - Estrazione Utenze TARI per Accesso Isola Ecologica');
Insert into EXPORT_PERSONALIZZATI ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) Values (445,'108009','Biassono - Estrazione Utenti TARI per SIELCO - Stazione Ecologica');
Insert into EXPORT_PERSONALIZZATI ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) Values (445,'012083','Induno Olona - Estrazione Utenti TARI per SIELCO - Stazione Ecologica');
Insert into EXPORT_PERSONALIZZATI ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) Values (446, '108009','Biassono - Estrazione Utenti TARI per Stazione Ecologica');
Insert into EXPORT_PERSONALIZZATI ( TIPO_EXPORT, CODICE_ISTAT, DESCRIZIONE) Values (446, '015093','Corsico - Estrazione Utenti TARI per Stazione Ecologica');

COMMIT;

ALTER TABLE export_personalizzati ENABLE ALL TRIGGERS;
