--liquibase formatted sql
--changeset dmarotta:20250326_152438_tiex_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE tipi_export DISABLE ALL TRIGGERS;

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (1, 'Dichiarazioni ANCI', 'TRAS_DICHIARAZIONI', 'S', 'wrk_tras_anci', 'D001.txt', null, 10, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (2, 'Rimborsi ICI', 'TRAS_RIMBORSI', 'S', 'wrk_tras_anci', 'R001.txt', null, 20, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (3, 'Stampa Rimborsi ICI', 'STAMPA_RIMBORSI', 'S', 'wrk_tras_anci', 'SR001.txt', null, 30, 'w_rimborsi_riscossioni_stampa_response', 'ICI', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (4, 'Riscossioni ICI', 'TRAS_RISCOSSIONI', 'S', 'wrk_tras_anci', 'A001.txt', null, 40, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (5, 'Stampa Riscossioni ICI', 'STAMPA_RISCOSSIONI', 'S', 'wrk_tras_anci', 'ST001.txt', null, 50, 'w_rimborsi_riscossioni_stampa_response', 'ICI', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (6, 'Riepilogo Riscossioni ICI', 'TRAS_TOT_RISCOSSIONI', 'S', 'wrk_tras_anci', 'T001.txt', null, 60, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (7, 'Estrazione Ruolo Poste (Vecchio Tracciato)', 'ESTRAZIONE_TARSU_POSTE', null, 'wrk_trasmissioni', 'V001.txt', null, 70, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (8, 'TARSU Agenzia Entrate (Utenze Attive)', 'ESTRAZIONE_TARSU_AGENZIA_OGVA', 'S', 'wrk_trasmissioni', 'G001.txt', null, 80, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (9, 'TARSU Agenzia Entrate (Variazioni)', 'ESTRAZIONE_TARSU_AGENZIA', 'S', 'wrk_trasmissioni', 'G001.txt', null, 90, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (10, 'Estrazione ICI Competenza', 'ESTRAZIONE_ICI_VERS', 'S', 'wrk_trasmissioni', 'V001.txt', null, 100, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (11, 'Estrazione ICI Cassa', 'ESTRAZIONE_ICI_VERS_CASSA', 'S', 'wrk_trasmissioni', 'V001.txt', null, 110, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (12, 'Estrazione Dati Vista Database', 'ESTRAZIONE_DATI_VISTA', 'S', 'wrk_trasmissioni', '_dati.txt', null, 120, null, 'TARSU', null, 'NOME_VISTA', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (13, 'Estrazione Ruolo Poste (Nuovo Tracciato)', 'ESTRAZIONE_TARSU_POSTE_2011', null, 'wrk_trasmissioni', 'V001.txt', null, 75, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (14, 'Estrazione TARI con F24', 'ESTRAZIONE_TARES_POSTE', 'S', 'wrk_trasmissioni', 'V001.txt', null, 80, null, 'TARSU', null, 'CODICE BELFIORE', null, null, 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (15, 'Estrazione TARI con F24 (Pontedera)', 'PON_ESTRAZIONE_TARES_POSTE', null, 'wrk_trasmissioni', 'V001.txt', null, 85, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (16, 'Estrazione TOSAP/COSAP con F24', 'ESTRAZIONE_COSAP_F24', 'S', 'wrk_trasmissioni', 'COSAP', null, null, null, 'TOSAP', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (17, 'Estrazione ICP/CIMP con F24', 'ESTRAZIONE_ICP_F24', 'S', 'wrk_trasmissioni', 'ICP', null, null, null, 'ICP', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (101, 'Estrazione ICI (Poste)', 'ESTRAZIONE_ICI_POSTE', null, 'wrk_trasmissioni', 'ici_poste.txt', null, null, null, 'ICI', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (102, 'Estrazione ICP (Poste)', 'ESTRAZIONE_ICP_POSTE', null, 'wrk_tras_anci', 'ICP001.txt', 5, null, null, 'ICP', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (103, 'Dichiarazioni ANCI Attive', 'TRAS_DICHIARAZIONI_CONT_ATT', null, 'wrk_tras_anci', 'IC01.txt', null, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (104, 'Estrazione ICI: Anagrafica', 'ESTRAZIONE_ICI_ANAGRAFICA', null, 'wrk_trasmissioni', 'E001.txt', null, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (105, 'Estrazione ICI: Immobili', 'ESTRAZIONE_ICI_IMMOBILI', null, 'wrk_trasmissioni', 'E002.txt', null, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (106, 'Bollettazione ICI', 'ESTRAI_BOLL_ICI', null, 'wrk_tras_anci', 'ICI001.txt', null, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (107, 'Bollettazione TARSU: Contribuenti', 'ESTRAI_BOLL_TARSU', null, 'wrk_tras_anci', 'RSU1001.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (108, 'Bollettazione TARSU: Oggetti', 'ESTRAI_BOLL_TARSU', null, 'wrk_tras_anci', 'RSU1001.txt', 1, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (109, 'Estrazione COSAP (Poste)', 'ESTRAZIONE_COSAP_POSTE', null, 'wrk_trasmissioni', 'V001.txt', null, null, null, 'TOSAP', 'w_chk_cont', 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (110, 'Trasmissione MAV', 'TRASMISSIONE_MAV', null, 'wrk_tras_anci', 'MAV001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (111, 'Estrazione TARSU GIT', 'ESTRAZIONE_TARSU_GIT', null, 'wrk_trasmissioni', '.txt', null, null, null, 'TARSU', null, 'TARSU BELFIORE DATA', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (112, 'Estrazione ICI GIT', 'ESTRAZIONE_ICI_GIT', null, 'wrk_trasmissioni', '.txt', null, null, null, 'ICI', null, 'ICI BELFIORE DATA', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (113, 'Estrazione Versamenti ICI GIT', 'ESTRAZIONE_VICI_GIT', null, 'wrk_trasmissioni', '.txt', null, null, null, 'ICI', null, 'VICI BELFIORE DATA', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (114, 'Abilitati Web Non Contribuenti', 'ABILITATI_WEB_NON_CONT', null, 'wrk_trasmissioni', 'abilitati_web_non_cont.txt', null, null, null, 'TRASV', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (151, 'ELIFIS Anagrafica dei Soggetti', 'TR4ER_ELIFIS.ANAGRAFICHE_SOGGETTI', null, 'wrk_trasmissioni', 'anagrafiche_soggetti_', null, 201, null, 'TRASV', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (152, 'ELIFIS Anagrafica degli Oggetti', 'TR4ER_ELIFIS.ANAGRAFICHE_OGGETTI', null, 'wrk_trasmissioni', 'anagrafiche_oggetti_', null, 202, null, 'TRASV', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (153, 'ELIFIS Comuni', 'TR4ER_ELIFIS.TRACCIATO_COMUNI', null, 'wrk_trasmissioni', 'comuni_', null, 203, null, 'TRASV', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (154, 'ELIFIS Nazioni', 'TR4ER_ELIFIS.TRACCIATO_NAZIONI', null, 'wrk_trasmissioni', 'nazioni_', null, 204, null, 'TRASV', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (155, 'ELIFIS Strade', 'TR4ER_ELIFIS.SIT_STRADE', null, 'wrk_trasmissioni', 'strade_', null, 205, null, 'TRASV', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (156, 'ELIFIS Civici', 'TR4ER_ELIFIS.SIT_CIVICI', null, 'wrk_trasmissioni', 'civici_', null, 206, null, 'TRASV', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (157, 'ELIFIS Denunce ICI', 'TR4ER_ELIFIS.DENUNCE_ICI', null, 'wrk_trasmissioni', 'denunce_ici_', null, 207, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (158, 'ELIFIS Aliquote Speciali ICI', 'TR4ER_ELIFIS.ALIQUOTE_SPECIALI_ICI', null, 'wrk_trasmissioni', 'aliquote_speciali_ici_', null, 208, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (159, 'ELIFIS Detrazioni ICI', 'TR4ER_ELIFIS.DETRAZIONI_ICI', null, 'wrk_trasmissioni', 'detrazioni_ici_', null, 209, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (160, 'ELIFIS Versamenti ICI', 'TR4ER_ELIFIS.VERSAMENTI_ICI', null, 'wrk_trasmissioni', 'versamenti_ici_', null, 210, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (161, 'ELIFIS Provvedimenti ICI', 'TR4ER_ELIFIS.PROVVEDIMENTI_ICI', null, 'wrk_trasmissioni', 'provvedimenti_ici_', null, 211, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (162, 'ELIFIS Dovuti ICI', 'TR4ER_ELIFIS.DOVUTI_ICI', null, 'wrk_trasmissioni', 'dovuti_ici_', null, 212, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (163, 'ELIFIS Aliquote ICI', 'TR4ER_ELIFIS.ALIQUOTE_ICI', null, 'wrk_trasmissioni', 'aliquote_ici_', null, 213, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (164, 'ELIFIS Agevolazioni ICI', 'TR4ER_ELIFIS.AGEVOLAZIONI_ICI', null, 'wrk_trasmissioni', 'agevolazioni_ici_', null, 214, null, 'ICI', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (165, 'ELIFIS Denunce RSU', 'TR4ER_ELIFIS.DENUNCE_RSU', null, 'wrk_trasmissioni', 'denunce_rsu_', null, 215, null, 'TARSU', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (166, 'ELIFIS Provvedimenti RSU', 'TR4ER_ELIFIS.PROVVEDIMENTI_RSU', null, 'wrk_trasmissioni', 'provvedimenti_rsu_', null, 216, null, 'TARSU', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (167, 'ELIFIS Classe Tariffa RSU', 'TR4ER_ELIFIS.CLASSE_TARIFFA_RSU', null, 'wrk_trasmissioni', 'classe_tariffa_rsu_', null, 217, null, 'TARSU', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (168, 'ELIFIS Tipi Oggetto RSU', 'TR4ER_ELIFIS.TIPI_OGGETTO_RSU', null, 'wrk_trasmissioni', 'tipi_oggetto_rsu_', null, 218, null, 'TARSU', null, null, 'TIMESTAMP', '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (201, 'Bollettini ICI Completi (Bel)', 'ESTRAI_BOLL_COMP_ICI_BEL', null, 'wrk_tras_anci', 'IC01.txt', 6, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (211, 'Bollettini ICI in bianco (Bov)', 'ESTRAI_BOLL_ICI_BOV', null, 'wrk_tras_anci', 'IB01.txt', 7, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (212, 'Bollettini ICI completi (Bov)', 'ESTRAI_BOLL_COMP_ICI_BOV', null, 'wrk_tras_anci', 'IC01.txt', 6, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (213, 'Trasmissione Fatture TIA RID (Bov)', 'TRASMISSIONE_FATTURA_RID_BOV', null, 'wrk_trasmissioni', 'TIA1001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (214, 'Trasmissione RID (Bov)', 'TRASMISSIONE_RID_BOV', null, 'wrk_tras_anci', 'RID1001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (215, 'Trasmissione Fatture TIA MAV (Bov)', 'TRASMISSIONE_FATTURA_MAV_BOV', null, 'wrk_trasmissioni', 'TIA1001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (216, 'Trasmissione MAV (Bov)', 'TRASMISSIONE_MAV_BOV', null, 'wrk_trasmissioni', 'MAV1001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (217, 'Bollettini TASI in bianco (Bov)', 'ESTRAI_BOLL_TASI_BOV', null, 'wrk_tras_anci', 'TB01.txt', 9, null, null, 'TASI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (218, 'Bollettini TASI completi (Bov)', 'ESTRAI_BOLL_COMP_TASI_BOV', null, 'wrk_tras_anci', 'TC01.txt', 8, null, null, 'TASI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (221, 'Bollettini ICI Completi (Cas)', 'ESTRAI_BOLL_COMP_ICI_CAS', null, 'wrk_tras_anci', 'IC01.txt', 6, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (231, 'Estrazione COSAP (Poste) (Marc)', 'ESTRAZIONE_COSAP_POSTE_MARC', null, 'wrk_trasmissioni', 'V001.txt', null, null, null, 'TOSAP', 'w_chk_cont', 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (241, 'Trasmissione MAV (Pio)', 'TRASMISSIONE_MAV_PIO', null, 'wrk_tras_anci', 'MAV1001.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (251, 'Dati TARSU: Anagrafe  (Pon)', 'TRAS_ANAGRAFE_TARSU_PON', null, 'wrk_trasmissioni', 'anagrafe_tarsu.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (252, 'Dati TARSU: Archivio Comuni (Pon)', 'TRAS_ARCHIVIO_COMUNI', null, 'wrk_trasmissioni', 'archivio_comuni.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (253, 'Dati TARSU: Archivio Vie (Pon)', 'TRAS_ARCHIVIO_VIE', null, 'wrk_trasmissioni', 'archivio_vie.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (261, 'Anagrafe TARSU (Mal)', 'TRAS_ANATARSU_MAL', null, 'wrk_trasmissioni', 'ANAGRA.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (262, 'Domicili TARSU (Mal)', 'TRAS_DOMTARSU_MAL', null, 'wrk_trasmissioni', 'DOMICILIO.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (263, 'Beni TARSU (Mal)', 'TRAS_BENITARSU_MAL', null, 'wrk_trasmissioni', 'BENI.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (271, 'Trasmissione MAV (Tra)', 'TRASMISSIONE_MAV_TRA', null, 'wrk_trasmissioni', 'MAV1001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (272, 'Trasmissione Fatture TIA (Seprio)', 'TRASMISSIONE_FATTURA_SER', null, 'wrk_trasmissioni', 'TIA1001.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (281, 'TARSU ENIA: Utenze TARSU/TIA (Sor)', 'TRASMISSIONE_TARSU_ENIA', null, 'wrk_trasmissioni', 'utenze_tarsu.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (282, 'TARSU ENIA: Archivio Categorie (Sor)', 'TRAS_CATEGORIE_ENIA', null, 'wrk_trasmissioni', 'categorie.txt', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (291, 'Conferitori (Val)', 'TRAS_CONFERITORI_VAL', null, 'wrk_trasmissioni', 'CN01.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (301, 'Trasmissione COSAP MAV (Cor)', 'TRASMISSIONE_COSAP_MAV', null, 'wrk_tras_anci', '_COSAP_MAV.txt', 0, null, null, 'TOSAP', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (302, 'Trasmissione Violazioni ICI MAV (Cor)', 'TRAS_MAV_ICI_VIOL_COR', null, 'wrk_tras_anci', '_ICIVI_MAV.txt', 0, null, null, 'ICI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (311, 'Trasmissione TARSU MAV (Lim)', 'TRASMISSIONE_MAV_LIM', null, 'wrk_tras_anci', '_TARSU_MAV.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (312, 'Trasmissione TARSU RID (Lim)', 'TRASMISSIONE_RID_LIM', null, 'wrk_tras_anci', '_TARSU_RID.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (321, 'Trasmissione TARSU MAV (SLS)', 'TRASMISSIONE_MAV_SLS', null, 'wrk_tras_anci', '_TARSU_MAV.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (322, 'Trasmissione TARSU RID su MAV (SLS)', 'TRASMISSIONE_RID_MAV_SLS', null, 'wrk_tras_anci', '_TARSU_RID_MAV.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (323, 'Estrazione Ecototem (SLS)', 'ESTRAZIONE_ECOTOTEM_SLS', null, 'wrk_trasmissioni', '_ECOTOTEM.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (324, 'Trasmissione TARSU RID (SLS)', 'TRASMISSIONE_RID_SLS', null, 'wrk_tras_anci', '_TARSU_RID.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (331, 'Trasmissione TARSU MAV (SGV)', 'TRASMISSIONE_MAV_SGV', null, 'wrk_tras_anci', '_TARSU_MAV.txt', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (341, 'Estrazione TARSU maggiorenni non morosi (ASA)', 'ESTRAZIONE_TARSU_ASA', null, 'wrk_trasmissioni', 'tarsu_maggiorenni.csv', null, null, null, 'TARSU', null, null, null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (351, 'Estrazione TARSU Unione Comuni (SIS)', 'ESTRAZIONE_TARSU_SIS', null, 'wrk_trasmissioni', 'tarsu_unione_', null, null, null, 'TARSU', null, null, 'CODICE BELFIORE', '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (352, 'F24 TASI completi', 'ESTRAI_F24_COMP_TASI', null, 'wrk_tras_anci', 'TC01.txt', 8, null, null, 'TASI', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (353, 'Estrazione Tarsu (Engineering)', 'ESTRAZIONE_TARSU_ENG', null, 'wrk_trasmissioni', '_TARSU_ENG.txt', null, null, null, 'TARSU', null, 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (354, 'Estrazione Accertamenti Automatici TARSU', 'ESTRAZIONE_ACC_TARSU_AUTO', null, 'wrk_trasmissioni', 'ACC_TARSU', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (361, 'ENG Tariffe', 'EXPENG.TARIFFE', null, 'wrk_trasmissioni', 'TARIFFE', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (362, 'ENG Anagrafe', 'EXPENG.ANAGRAFE', null, 'wrk_trasmissioni', 'TARCONTR', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (363, 'ENG Utenze', 'EXPENG.UTENZE', null, 'wrk_trasmissioni', 'NTAUTENZ', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (364, 'ENG Provvedimenti', 'EXPENG.PROVVEDIMENTI', null, 'wrk_trasmissioni', 'TARUTENZ', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (365, 'ENG Versamenti Omessi', 'EXPENG.VERSAMENTI_OMESSI', null, 'wrk_trasmissioni', 'TARVEROME', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (366, 'ENG Versamenti Parziali', 'EXPENG.VERSAMENTI_PARZIALI', null, 'wrk_trasmissioni', 'TARVERPAR', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (367, 'Estrazione Accertamenti TARES/TIA/TARI (SLS)', 'EXPENG.ACCERTAMENTI', null, 'wrk_trasmissioni', 'TARACC', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (371, 'STD Comuni Esteri', 'EXPSTD.COMUNI', null, 'wrk_trasmissioni', 'COMUNI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (372, 'STD Stradario', 'EXPSTD.STRADARIO', null, 'wrk_trasmissioni', 'STRADARIO', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (373, 'STD Anagrafe', 'EXPSTD.ANAGRAFE', null, 'wrk_trasmissioni', 'ANAGRAFE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (374, 'STD Aliquote', 'EXPSTD.ALIQUOTE', null, 'wrk_trasmissioni', 'ALIQUOTE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (375, 'STD Categorie Catasto', 'EXPSTD.CATEGORIE_CATASTO', null, 'wrk_trasmissioni', 'CATEGORIE_CATASTO', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (376, 'STD Detrazioni', 'EXPSTD.DETRAZIONI', null, 'wrk_trasmissioni', 'DETRAZIONI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (377, 'STD Fonti', 'EXPSTD.FONTI', null, 'wrk_trasmissioni', 'FONTI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (378, 'STD Moltiplicatori', 'EXPSTD.MOLTIPLICATORI', null, 'wrk_trasmissioni', 'MOLTIPLICATORI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (379, 'STD Motivi Detrazione', 'EXPSTD.MOTIVI_DETRAZIONE', null, 'wrk_trasmissioni', 'MOTIVI_DETRAZIONE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (380, 'STD Rivalutazioni Rendita', 'EXPSTD.RIVALUTAZIONI_RENDITA', null, 'wrk_trasmissioni', 'RIVALUTAZIONI_RENDITA', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (381, 'STD Tipi Aliquota', 'EXPSTD.TIPI_ALIQUOTA', null, 'wrk_trasmissioni', 'TIPI_ALIQUOTA', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (382, 'STD Tipi Carica', 'EXPSTD.TIPI_CARICA', null, 'wrk_trasmissioni', 'TIPI_CARICA', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (383, 'STD Tipi Stato', 'EXPSTD.TIPI_STATO', null, 'wrk_trasmissioni', 'TIPI_STATO', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (384, 'STD Tipi Uso', 'EXPSTD.TIPI_USO', null, 'wrk_trasmissioni', 'TIPI_USO', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (385, 'STD Tipi Utilizzo', 'EXPSTD.TIPI_UTILIZZO', null, 'wrk_trasmissioni', 'TIPI_UTILIZZO', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (386, 'STD Immobili', 'EXPSTD.IMMOBILI', null, 'wrk_trasmissioni', 'IMMOBILI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (387, 'STD Riferimenti Immobile', 'EXPSTD.RIFERIMENTI_IMMOBILE', null, 'wrk_trasmissioni', 'RIFERIMENTI_IMMOBILE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (388, 'STD Utilizzi Immobile', 'EXPSTD.UTILIZZI_IMMOBILE', null, 'wrk_trasmissioni', 'UTILIZZI_IMMOBILE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (389, 'STD Denunce', 'EXPSTD.DENUNCE', null, 'wrk_trasmissioni', 'DENUNCE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (390, 'STD Dettagli Denuncia', 'EXPSTD.DETTAGLI_DENUNCIA', null, 'wrk_trasmissioni', 'DETTAGLI_DENUNCIA', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (391, 'STD Aliquote Immobile', 'EXPSTD.ALIQUOTE_IMMOBILE', null, 'wrk_trasmissioni', 'ALIQUOTE_IMMOBILE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (392, 'STD Detrazioni Immobile', 'EXPSTD.DETRAZIONI_IMMOBILE', null, 'wrk_trasmissioni', 'DETRAZIONI_IMMOBILE', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (393, 'STD Detrazioni Figli', 'EXPSTD.DETRAZIONI_FIGLI', null, 'wrk_trasmissioni', 'DETRAZIONI_FIGLI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (394, 'STD Maggiori Detrazioni', 'EXPSTD.MAGGIORI_DETRAZIONI', null, 'wrk_trasmissioni', 'MAGGIORI_DETRAZIONI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (395, 'STD Provvedimenti', 'EXPSTD.PROVVEDIMENTI', null, 'wrk_trasmissioni', 'PROVVEDIMENTI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (396, 'STD Versamenti', 'EXPSTD.VERSAMENTI', null, 'wrk_trasmissioni', 'VERSAMENTI', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (397, 'STD Contatti Contribuente', 'EXPSTD.CONTATTI_CONTRIBUENTE', null, 'wrk_trasmissioni', 'CONTATTI', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (398, 'STD Sanzioni Provvedimento', 'EXPSTD.SANZIONI_PROVVEDIMENTO', null, 'wrk_trasmissioni', 'SANZIONI_PROVVEDIMENTO', null, null, null, null, null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (411, 'Denunce (vers. Omnia)', 'OMNIA.EXP_DENUNCE', null, 'wrk_trasmissioni', 'DENUNCE_OMNIA', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (412, 'Dettagli Denuncia (vers. Omnia)', 'OMNIA.EXP_DETTAGLI_DENUNCIA', null, 'wrk_trasmissioni', 'DETTAGLI_DENUNCIA_OMNIA', null, null, null, 'ICI', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (421, 'Estrazione Dovuto Versato TARSU per F24', 'ESTRAZIONE_DV_TARSU_F24', null, 'wrk_trasmissioni', 'DOVUTO_VERSATO_TARI_F24', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (422, 'Estrazione COSAP (Cor)', 'ESTRAZIONE_COSAP_COR', null, 'wrk_trasmissioni', 'ESTRAZIONE_COSAP', null, null, null, 'TOSAP', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (423, 'Estrazione Avvisi Liquidazione IMU', 'ESTRAZIONE_LIQUIDAZIONI_IMU', null, 'wrk_trasmissioni', 'LIQ_IMU', null, null, null, 'ICI', null, null, null, '.txt', 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (424, 'Estrazione COSAP (Poste) (Prov. di Pistoia)', 'ESTRAZIONE_COSAP_POSTE_PT', null, 'wrk_trasmissioni', 'V001.txt', null, null, null, 'TOSAP', 'w_chk_cont', 'CODICE BELFIORE', null, null, null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (425, 'GEOFOR - Estrazione file completo', 'CER_CONFERIMENTI.ESTRAZIONE_FILE_COMPLETO', null, 'wrk_trasmissioni', 'completo_pontedera', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (426, 'Estrazione Avvisi Liquidazione TASI', 'ESTRAZIONE_LIQUIDAZIONI_TASI', null, 'wrk_trasmissioni', 'LIQ_TASI', null, null, null, 'TASI', null, null, null, '.txt', 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (427, 'Estrazione TARI per Garbage (Reggello/Pontassieve)', 'ESTRAZIONE_TARI_GARBAGE', null, 'wrk_trasmissioni', 'GARBAGE', null, null, null, 'TARSU', null, null, null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (428, 'Trasmissione TARI RID', 'TRASMISSIONE_RID_STD', null, 'wrk_tras_anci', '_TARI_RID', 0, null, null, 'TARSU', null, 'CODICE BELFIORE', null, '.txt', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (429, 'Estrazione TARI per ASPEM', 'ESTRAZIONE_TARI_ASPEM', null, 'wrk_trasmissioni', 'ASPEM', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (430, 'Estrazione Utenze TARI (S.Gimignano)', 'UTENZE_TARSU_FTP.ESTRAZIONE_UTENZE_TARSU', null, 'wrk_trasmissioni', 'UTENZE_TARI', null, null, null, 'TARSU', null, null, 'TIMESTAMP', '.csv', 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (431, 'Estrazione Ruolo TARI per HERA', 'ESTRAZIONE_RUOLO_TARSU_HERA', null, 'wrk_trasmissioni', 'ESTR_RUOLO_HERA', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (432, 'Estrazione Utenze TARI per ECUOSACCO', 'ESTRAZIONE_TARI_ECUOSACCO', null, 'wrk_trasmissioni', 'UTENTI', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (441, 'Estrazione Ruolo TARI per Solori - Dati Generali', 'EXPTARI_VALEGGIO.DATI_GENERALI', null, 'wrk_trasmissioni', 'TAREXPFA', null, null, null, 'TARSU', null, null, null, '.txt', 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (442, 'Estrazione Ruolo TARI per Solori - Testate Fattura', 'EXPTARI_VALEGGIO.TESTATE_FATTURA', null, 'wrk_trasmissioni', 'TAREXPFB', null, null, null, 'TARSU', null, null, null, '.txt', 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (443, 'Estrazione Ruolo TARI per Solori - Dettagli Fattura', 'EXPTARI_VALEGGIO.DETTAGLI_FATTURA', null, 'wrk_trasmissioni', 'TAREXPFC', null, null, null, 'TARSU', null, null, null, '.txt', 'S');

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (444, 'Estrazione Utenti TARI per Accesso a Isola Ecologica - San Donato Milanese', 'ESTRAZIONE_UTENTI_TARI_SDM', null, 'wrk_trasmissioni', 'UTENTI_TARI', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (445, 'Estrazione TARI per SIELCO - Isola Ecologica', 'ESTRAZIONE_TARI_FTP.ESTRAZIONE_TARI_SIELCO', null, 'wrk_trasmissioni', 'UTENTI_TARI', null, null, null, 'TARSU', null, null, null, '.csv', null);

insert into tipi_export (TIPO_EXPORT, DESCRIZIONE, NOME_PROCEDURA, FLAG_STANDARD, TABELLA_TEMPORANEA, NOME_FILE, ANNO_TRAS_ANCI, ORDINAMENTO, WINDOW_STAMPA, TIPO_TRIBUTO, WINDOW_CONTROLLO, PREFISSO_NOME_FILE, SUFFISSO_NOME_FILE, ESTENSIONE_NOME_FILE, FLAG_CLOB)
values (446, 'Estrazione TARI per CORSICO - Isola Ecologica', 'ESTRAZIONE_TARI_FTP.ESTRAZIONE_TARI_CORSICO', null, 'wrk_trasmissioni', 'UTENTI_TARI', null, null, null, 'TARSU', null, null, null, '.csv', null);

ALTER TABLE tipi_export ENABLE ALL TRIGGERS;
