--liquibase formatted sql
--changeset dmarotta:20250326_152438_timo_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE tipi_modello DISABLE ALL TRIGGERS;

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_CUNI%', 'ACC AUTO PER OMESSO O PARZIALE VERSAMENTO', 'A', 'A', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_D_ICI%', 'ACC PER OMESSA O INFEDELE DENUNCIA', 'A', 'U', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_D_TAR%', 'ACC PER OMESSA O INFEDELE DENUNCIA', 'A', 'U', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_ICI%', 'ACCERTAMENTO ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_ICIAP%', 'ACCERTAMENTO ICIAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_ICP%', 'ACC AUTO PER OMESSO O PARZIALE VERSAMENTO', 'A', 'A', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_TARIR%', 'ACCERTAMENTO TARI A RIMBORSO', 'A', null, 'S');

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_TARSU%', 'ACC AUTO PER OMESSO O PARZIALE PAGAMENTO', 'A', 'A', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_TASI%', 'ACCERTAMENTO TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_T_ICI%', 'ACCERTAMENTO TOTALE ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_TOSAP%', 'ACC AUTO PER OMESSO O PARZIALE VERSAMENTO', 'A', 'A', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_T_TAR%', 'ACCERTAMENTO TOTALE TARSU', 'A', 'T', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ACC_T_TAS%', 'ACCERTAMENTO TOTALE TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ANO%', 'ANOMALIA SOGEI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('CES_ICP%', 'AUTODENUNCIA DI CESSAZIONE ICP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('CES_TARSU%', 'AUTODENUNCIA DI CESSAZIONE', 'D', 'C', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('CES_TOSAP%', 'AUTODENUNCIA DI CESSAZIONE TOSAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_COSAP%', 'COMUNICAZIONE COSAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_CUNI%', 'COMUNICAZIONE CANONE UNICO', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_ICI%', 'COMUNICAZIONE IMU', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_ICP%', 'COMUNICAZIONE ICP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_TARSU%', 'COMUNICAZIONE A RUOLO', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_TASI%', 'COMUNICAZIONE TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('COM_TOSAP%', 'COMUNICAZIONE TOSAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('CONC_TOSAP', 'CONCESSIONE TOSAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DEIC%', 'AUTODENUNCIA ICI', 'D', null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DEPB%', 'AUTODENUNCIA DI ISCRIZIONE ICP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DETA%', 'AUTODENUNCIA DI ISCRIZIONE', 'D', 'I', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DETO%', 'AUTODENUNCIA DI ISCRIZIONE TOSAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DOV%', 'DOVUTO VERSATO', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DOV_ICP%', 'DOVUTO VERSATO ICP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DOV_TARSU%', 'DOVUTO VERSATO TARSU', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DOV_TASI%', 'DOVUTO VERSATO TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('DOV_TOSAP%', 'DOVUTO VERSATO TOSAP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('FAT_TARSU%', 'FATTURA TIA', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('GEN%', 'LETTERA GENERICA', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('INF%', 'INFRAZIONE FORMALE', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ING_A_ICI%', 'INGIUNZIONE PAGAMENTO ACCERTAMENTO ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ING_A_TAS%', 'INGIUNZIONE PAGAMENTO ACCERTAMENTO TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ING_L_ICI%', 'INGIUNZIONE PAGAMENTO LIQUIDAZIONE ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ING_L_TAS%', 'INGIUNZIONE PAGAMENTO LIQUIDAZIONE TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ING_TARSU%', 'INGIUNZIONE TARSU', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('ING_TRASV%', 'INGIUNZIONE', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('INL%', 'IMMOBILI NON LIQUIDABILI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('IST_TRASV%', 'ACCOGLIMENTO ISTANZA', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('LIQ_ICI%', 'LIQUIDAZIONE ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('LIQ_ICIR%', 'LIQUIDAZIONE ICI A RIMBORSO', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('LIQ_IMU%', 'LIQUIDAZIONE IMU', 'L', null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('LIQ_IMUR%', 'LIQUIDAZIONE IMU A RIMBORSO', 'L', null, 'S');

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('LIQ_TASI%', 'LIQUIDAZIONE TASI', 'L', null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('LIQ_TASIR%', 'LIQUIDAZIONE TASI A RIMBORSO', 'L', null, 'S');

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('RIM_ICI%', 'LETTERA DI RIMBORSO ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('RIM_TARSU%', 'LETTERA DI RIMBORSO TARSU', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SG_ICI%', 'LETTERA DI SGRAVIO ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SGR%', 'LETTERA DI SGRAVIO', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SGRC%', 'LETTERA DI SGRAVIO', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_A_ICI%', 'SOLLECITO PAGAMENTO ACCERTAMENTO ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_A_TAS%', 'SOLLECITO PAGAMENTO ACCERTAMENTO TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_CUNI%', 'SOLLECITO PAGAMENTO CANONE UNICO', 'S', 'A', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_ICP%', 'SOLLECITO PAGAMENTO ICP ', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_L_ICI%', 'SOLLECITO PAGAMENTO LIQUIDAZIONE ICI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_L_TAS%', 'SOLLECITO PAGAMENTO LIQUIDAZIONE TASI', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_TARSU%', 'SOLLECITO PAGAMENTO TARSU', 'S', 'A', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('SOL_TOSAP%', 'SOLLECITO PAGAMENTO TOSAP ', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('VAR_ICP%', 'AUTODENUNCIA DI VARIAZIONE ICP', null, null, null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('VAR_TARSU%', 'AUTODENUNCIA DI VARIAZIONE', 'D', 'V', null);

insert into tipi_modello (TIPO_MODELLO, DESCRIZIONE, TIPO_PRATICA, TIPO_EVENTO, FLAG_RIMBORSO)
values ('VAR_TOSAP%', 'AUTODENUNCIA DI VARIAZIONE TOSAP', null, null, null);

ALTER TABLE tipi_modello ENABLE ALL TRIGGERS;
