--liquibase formatted sql
--changeset dmarotta:20250326_152438_tire_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE tipi_recapito DISABLE ALL TRIGGERS;

INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (1,'INDIRIZZO');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (2,'E-MAIL');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (3,'E-MAIL PEC');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (4,'TELEFONO');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (5,'FAX');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (6,'CELLULARE PERSONALE');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (7,'CELLULALRE LAVORO');
INSERT INTO tipi_recapito ( TIPO_RECAPITO, DESCRIZIONE) VALUES (10,'IBAN');

ALTER TABLE tipi_recapito ENABLE ALL TRIGGERS;
