--liquibase formatted sql
--changeset dmarotta:20250326_152438_tisp_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE tipi_spedizione DISABLE ALL TRIGGERS;

INSERT INTO tipi_spedizione ( TIPO_SPEDIZIONE, DESCRIZIONE) VALUES ('AG','RACCOMANDATA ATTI GIUDIZIARI');
INSERT INTO tipi_spedizione ( TIPO_SPEDIZIONE, DESCRIZIONE) VALUES ('AR','RACCOMANDATA AR');
INSERT INTO tipi_spedizione ( TIPO_SPEDIZIONE, DESCRIZIONE) VALUES ('CC','CONSEGNA IN COMUNE');
INSERT INTO tipi_spedizione ( TIPO_SPEDIZIONE, DESCRIZIONE) VALUES ('PM','POSTA ORDINARIA');
INSERT INTO tipi_spedizione ( TIPO_SPEDIZIONE, DESCRIZIONE) VALUES ('PP','POSTA PRIORITARIA');

ALTER TABLE tipi_spedizione ENABLE ALL TRIGGERS;
