--liquibase formatted sql
--changeset dmarotta:20250326_152438_wdca_ins stripComments:false
--validCheckSum: 1:any

ALTER TABLE wrk_docfa_causali DISABLE ALL TRIGGERS;

INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('AFF','DENUNCIA DI UNITA'' AFFERENTE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('AMP','AMPLIAMENTO');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('DEP','DEMOLIZIONE PARZIALE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('DET','DEMOLIZIONE TOTALE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('DIV','DIVISIONE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('FRF','FRAZIONAMENTO E FUSIONE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('FRZ','FRAZIONAMENTO');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('FUS','FUSIONE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('NC','ACCATASTAMENTO');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('RST','RISTRUTTURAZIONE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('UFU','ULTIMAZIONE FABBRICATO URBANO');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('VAR','ALTRE VARIAZIONI');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('VDE','VARIAZIONE DELLA DESTINAZIONE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('VMI','MODIFICA DI IDENTIFICATIVO');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('VRP','PRESENTAZIONE DI PLANIMETRIA MANCANTE');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('VSI','VARIAZIONE SPAZI INTERNI');
INSERT INTO wrk_docfa_causali ( CAUSALE, DESCRIZIONE) VALUES ('VTO','VARIAZIONE TOPONOMASTICA');

ALTER TABLE wrk_docfa_causali ENABLE ALL TRIGGERS;
