package it.finmatica.tr4.contribuenti.f24query

class F24ImpostaQuery {

    static def query(String tipoTributo, String tipo = 'I') {
        return """
         select '$tipo' as tipo,
                '$tipoTributo' as tipo_tributo,
                    (select case
                             when '$tipoTributo' in ('ICI', 'TASI') and :p_tipo_versamento in ('A', 'S') then
                              f_descrizione_titr('$tipoTributo', :p_anno) ||
                              decode(:p_tipo_versamento, 'A', ' acconto', 'S', ' saldo') ||
                               ' - Scadenza ' || to_char(scad.data_scadenza, 'DD/MM/YYYY')
                             else
                              ''
                           end
                      from scadenze scad
                     where scad.tipo_tributo = '$tipoTributo'
                       and scad.anno = :p_anno
                       and scad.tipo_versamento = :p_tipo_versamento)  titolo_f24,
               contribuenti.cod_fiscale,
               translate(soggetti.cognome_nome, '/', ' ') csoggnome,
               decode(soggetti.cod_via,
                      null,
                      soggetti.denominazione_via,
                      archivio_vie.denom_uff) ind,
               soggetti.num_civ num_civ,
               soggetti.suffisso suff,
               decode(soggetti.cod_via,
                      null,
                      soggetti.denominazione_via,
                      archivio_vie.denom_uff) ||
               decode(soggetti.num_civ, null, '', ', ' || soggetti.num_civ) ||
               decode(soggetti.suffisso, null, '', '/' || soggetti.suffisso) indirizzo_dich,
               ad4_comuni_a.denominazione comune,
               ad4_provincie_a.sigla provincia,
               ad4_comuni_b.denominazione comune_nas,
               ad4_provincie_b.sigla provincia_nas,
               soggetti.sesso sesso,
               soggetti.cognome cognome,
               soggetti.nome nome,
               to_char(soggetti.data_nas, 'yyyy') anno_nascita,
               to_char(soggetti.data_nas, 'mm') mese_nascita,
               to_char(soggetti.data_nas, 'dd') giorno_nascita,
               to_char(:p_anno, '9999') anno,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 1),
                                5,
                                10)) importo_riga_1,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 2),
                                5,
                                10)) importo_riga_2,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 3),
                                5,
                                10)) importo_riga_3,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 4),
                                5,
                                10)) importo_riga_4,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 5),
                                5,
                                10)) importo_riga_5,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 6),
                                5,
                                10)) importo_riga_6,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 7),
                                5,
                                10)) importo_riga_7,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 8),
                                5,
                                10)) importo_riga_8,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 9),
                                5,
                                10)) importo_riga_9,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 10),
                                5,
                                10)) importo_riga_10,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       1),
                      1,
                      4) cotr_riga_1,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       2),
                      1,
                      4) cotr_riga_2,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       3),
                      1,
                      4) cotr_riga_3,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       4),
                      1,
                      4) cotr_riga_4,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       5),
                      1,
                      4) cotr_riga_5,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       6),
                      1,
                      4) cotr_riga_6,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       7),
                      1,
                      4) cotr_riga_7,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       8),
                      1,
                      4) cotr_riga_8,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       9),
                      1,
                      4) cotr_riga_9,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       10),
                      1,
                      4) cotr_riga_10,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       1),
                      15,
                      4) n_fab_riga_1,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       2),
                      15,
                      4) n_fab_riga_2,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       3),
                      15,
                      4) n_fab_riga_3,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       4),
                      15,
                      4) n_fab_riga_4,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       5),
                      15,
                      4) n_fab_riga_5,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       6),
                      15,
                      4) n_fab_riga_6,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       7),
                      15,
                      4) n_fab_riga_7,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       8),
                      15,
                      4) n_fab_riga_8,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       9),
                      15,
                      4) n_fab_riga_9,
               substr(f_f24_tributiweb(:p_tipo_tributo,
                                       :p_cod_fiscale,
                                       :p_anno,
                                       :p_tipo_versamento,
                                       :p_dovuto_versato,
                                       10),
                      15,
                      4) n_fab_riga_10,
               to_number(substr(f_f24_tributiweb(:p_tipo_tributo,
                                                 :p_cod_fiscale,
                                                 :p_anno,
                                                 :p_tipo_versamento,
                                                 :p_dovuto_versato,
                                                 1),
                                20,
                                10)) detr,
               decode(:p_tipo_versamento, 'S', ' ', 'X') acconto,
               decode(:p_tipo_versamento, 'A', ' ', 'X') saldo,
               ad4_comuni_c.sigla_cfis codice_comune,
               decode(to_number(to_char(sysdate, 'yyyy')),
                      to_number(to_char(:p_anno, '9999')),
                      '',
                      'X') anno_imposta_diverso_solare,
               f_primo_erede_cod_fiscale(soggetti.ni) cod_fiscale_erede
          from ad4_comuni    ad4_comuni_a,
               ad4_provincie ad4_provincie_a,
               archivio_vie,
               soggetti,
               contribuenti,
               ad4_comuni    ad4_comuni_b,
               ad4_provincie ad4_provincie_b,
               dati_generali dage,
               ad4_comuni    ad4_comuni_c
         where ad4_comuni_a.provincia_stato = ad4_provincie_a.provincia(+)
           and soggetti.cod_pro_res = ad4_comuni_a.provincia_stato(+)
           and soggetti.cod_com_res = ad4_comuni_a.comune(+)
           and soggetti.cod_via = archivio_vie.cod_via(+)
           and ad4_comuni_b.provincia_stato = ad4_provincie_b.provincia(+)
           and soggetti.cod_pro_nas = ad4_comuni_b.provincia_stato(+)
           and soggetti.cod_com_nas = ad4_comuni_b.comune(+)
           and soggetti.cod_via = archivio_vie.cod_via(+)
           and dage.pro_cliente = ad4_comuni_c.provincia_stato
           and dage.com_cliente = ad4_comuni_c.comune
           and contribuenti.ni = soggetti.ni
           and contribuenti.cod_fiscale = :p_cod_fiscale
                    """
    }

}
