package it.finmatica.tr4.contribuenti.f24query

class F24RavvICIQuery {

    static def query() {
        return """
                select prtr.tipo_tributo as tributo,
                       contribuenti.cod_fiscale,
                       translate(soggetti.cognome_nome, '/', ' ') csoggnome,
                       decode(soggetti.cod_via,
                              null,
                              soggetti.denominazione_via,
                              archivio_vie.denom_uff) ind,
                       soggetti.num_civ num_civ,
                       soggetti.suffisso suff,
                       decode(soggetti.cod_via,
                              null,
                              soggetti.denominazione_via,
                              archivio_vie.denom_uff) ||
                       decode(soggetti.num_civ, null, '', ', ' || soggetti.num_civ) ||
                       decode(soggetti.suffisso, null, '', '/' || soggetti.suffisso) indirizzo_dich,
                       ad4_comuni_a.denominazione comune,
                       ad4_provincie_a.sigla provincia,
                       ad4_comuni_b.denominazione comune_nas,
                       ad4_provincie_b.sigla provincia_nas,
                       soggetti.sesso sesso,
                       soggetti.cognome cognome,
                       soggetti.nome nome,
                       to_char(soggetti.data_nas, 'yyyy') anno_nascita,
                       to_char(soggetti.data_nas, 'mm') mese_nascita,
                       to_char(soggetti.data_nas, 'dd') giorno_nascita,
                       to_char(prtr.anno) anno,
                       to_number(substr(f_f24_imu(1,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_1,
                       to_number(substr(f_f24_imu(2,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_2,
                       to_number(substr(f_f24_imu(3,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_3,
                       to_number(substr(f_f24_imu(4,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_4,
                       to_number(substr(f_f24_imu(5,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_5,
                       to_number(substr(f_f24_imu(6,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_6,
                       to_number(substr(f_f24_imu(7,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_7,
                       to_number(substr(f_f24_imu(8,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_8,
                       to_number(substr(f_f24_imu(9,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_9,
                       to_number(substr(f_f24_imu(10,
                                                  sanz.ab_principale,
                                                  sanz.rurali,
                                                  sanz.terreni_comune,
                                                  sanz.terreni_erariale,
                                                  sanz.aree_comune,
                                                  sanz.aree_erariale,
                                                  sanz.altri_comune,
                                                  sanz.altri_erariale,
                                                  vido.num_fabbricati_ab_imu,
                                                  vido.num_fabbricati_rurali_imu,
                                                  vido.num_fabbricati_altri_imu,
                                                  sanz.fabbricati_d_comune,
                                                  sanz.fabbricati_d_erariale,
                                                  vido.num_fabbricati_fabb_d_imu),
                                        5,
                                        10)) importo_riga_10,
                       substr(f_f24_imu(1,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_1,
                       substr(f_f24_imu(2,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_2,
                       substr(f_f24_imu(3,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_3,
                       substr(f_f24_imu(4,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_4,
                       substr(f_f24_imu(5,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_5,
                       substr(f_f24_imu(6,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_6,
                       substr(f_f24_imu(7,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_7,
                       substr(f_f24_imu(8,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_8,
                       substr(f_f24_imu(9,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_9,
                       substr(f_f24_imu(10,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              1,
                              4) cotr_riga_10,
                       substr(f_f24_imu(1,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_1,
                       substr(f_f24_imu(2,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_2,
                       substr(f_f24_imu(3,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_3,
                       substr(f_f24_imu(4,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_4,
                       substr(f_f24_imu(5,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_5,
                       substr(f_f24_imu(6,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_6,
                       substr(f_f24_imu(7,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_7,
                       substr(f_f24_imu(8,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_8,
                       substr(f_f24_imu(9,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_9,
                       substr(f_f24_imu(10,
                                        sanz.ab_principale,
                                        sanz.rurali,
                                        sanz.terreni_comune,
                                        sanz.terreni_erariale,
                                        sanz.aree_comune,
                                        sanz.aree_erariale,
                                        sanz.altri_comune,
                                        sanz.altri_erariale,
                                        vido.num_fabbricati_ab_imu,
                                        vido.num_fabbricati_rurali_imu,
                                        vido.num_fabbricati_altri_imu,
                                        sanz.fabbricati_d_comune,
                                        sanz.fabbricati_d_erariale,
                                        vido.num_fabbricati_fabb_d_imu),
                              15,
                              4) n_fab_riga_10,
                       translate(to_char(decode(sanz.se_acconto || sanz.se_saldo,
                                                'AS',
                                                vido.detrazione,
                                                'A',
                                                vido.detrazione_acconto,
                                                'S',
                                                vido.detrazione_saldo,
                                                null),
                                         '999,999,990.00'),
                                 ',.',
                                 '.,') detr,
                       decode(sanz.se_acconto, 'A', 'X', ' ') acconto,
                       decode(sanz.se_saldo, 'S', 'X', ' ') saldo,
                       ad4_comuni_c.sigla_cfis codice_comune,
                       decode(to_number(to_char(sysdate, 'yyyy')),
                              to_number(to_char(prtr.anno, '9999')),
                              '',
                              'X') anno_imposta_diverso_solare,
                       f_primo_erede_cod_fiscale(soggetti.ni) cod_fiscale_erede,
                       'X' ravvedimento,
                       'RAVP' || to_char(prtr.anno) || lpad(to_char(prtr.pratica), 10, '0') identificativo_operazione
                  from ad4_comuni ad4_comuni_a,
                       ad4_provincie ad4_provincie_a,
                       archivio_vie,
                       soggetti,
                       contribuenti,
                       ad4_comuni ad4_comuni_b,
                       ad4_provincie ad4_provincie_b,
                       dati_generali dage,
                       ad4_comuni ad4_comuni_c,
                       violazioni_dettagli_ogim vido,
                       pratiche_tributo prtr,
                       (select sum(ab_principale) ab_principale,
                               sum(rurali) rurali,
                               sum(terreni_comune) terreni_comune,
                               sum(terreni_erariale) terreni_erariale,
                               sum(aree_comune) aree_comune,
                               sum(aree_erariale) aree_erariale,
                               sum(altri_comune) altri_comune,
                               sum(altri_erariale) altri_erariale,
                               sum(fabbricati_d_comune) fabbricati_d_comune,
                               sum(fabbricati_d_erariale) fabbricati_d_erariale,
                               sapr.pratica,
                               max(decode(sapr.cod_sanzione, '101', 'A', null)) se_acconto,
                               max(decode(sapr.cod_sanzione, '121', 'S', null)) se_saldo
                          from sanzioni_pratica sapr
                         group by sapr.pratica) sanz
                 where ad4_comuni_a.provincia_stato = ad4_provincie_a.provincia(+)
                   and soggetti.cod_pro_res = ad4_comuni_a.provincia_stato(+)
                   and soggetti.cod_com_res = ad4_comuni_a.comune(+)
                   and soggetti.cod_via = archivio_vie.cod_via(+)
                   and ad4_comuni_b.provincia_stato = ad4_provincie_b.provincia(+)
                   and soggetti.cod_pro_nas = ad4_comuni_b.provincia_stato(+)
                   and soggetti.cod_com_nas = ad4_comuni_b.comune(+)
                   and soggetti.cod_via = archivio_vie.cod_via(+)
                   and dage.pro_cliente = ad4_comuni_c.provincia_stato
                   and dage.com_cliente = ad4_comuni_c.comune
                   and contribuenti.ni = soggetti.ni
                   and contribuenti.cod_fiscale = prtr.cod_fiscale
                   and prtr.pratica = vido.pratica(+)
                   and prtr.pratica = sanz.pratica(+)
                   and prtr.pratica = :pPratica
                   and prtr.anno >= 2012
                 order by soggetti.cognome_nome

                    """
    }

}
