package it.finmatica.tr4.contribuenti.f24query

class F24RavvTARSUQuery {

    static def query() {

        // ATTENZIONE: la condizione and :pCodFiscale = :pCodFiscale è per rendere compatibile l'esecuzione della query
        // con quella delle violazioni TARSU che prende in input il parametro :pCodFiscale

        // Nota : per i Ravvedimenti si vuole Imposta + Sanzioni + Interessi sul 3944
        //        Se anno >= 2021 la TEFA va scorporata e contabilizzata a parte come codice TEFA

        return """
                select prat.tipo_tributo as tributo,
                       prat.numero ord2,
                       contribuenti.cod_fiscale,
                       translate(soggetti.cognome_nome, '/', ' ') csoggnome,
                       decode(soggetti.cod_via,
                              null,
                              soggetti.denominazione_via,
                              archivio_vie.denom_uff) ind,
                       soggetti.num_civ num_civ,
                       soggetti.suffisso suff,
                       decode(soggetti.cod_via,
                              null,
                              soggetti.denominazione_via,
                              archivio_vie.denom_uff) ||
                       decode(soggetti.num_civ, null, '', ', ' || soggetti.num_civ) ||
                       decode(soggetti.suffisso, null, '', '/' || soggetti.suffisso) indirizzo_dich,
                       ad4_comuni_a.denominazione comune,
                       ad4_provincie_a.sigla provincia,
                       ad4_comuni_b.denominazione comune_nas,
                       ad4_provincie_b.sigla provincia_nas,
                       soggetti.sesso sesso,
                       soggetti.cognome cognome,
                       soggetti.nome nome,
                       to_char(soggetti.data_nas, 'yyyy') anno_nascita,
                       to_char(soggetti.data_nas, 'mm') mese_nascita,
                       to_char(soggetti.data_nas, 'dd') giorno_nascita,
                       to_char(prat.anno) anno,
                       case
                         when prat.anno < 2021 then
                          to_number(substr(f_f24_acc_tares(1,
                                                           prat.importo_tari_tassa,
                                                           prat.interessi_tari_tassa,
                                                           prat.sanzioni_tari_tassa,
                                                           prat.importo_tariffa,
                                                           prat.interessi_tariffa,
                                                           prat.sanzioni_tariffa,
                                                           prat.maggiorazione,
                                                           prat.interessi_maggiorazione,
                                                           prat.sanzioni_maggiorazione),
                                           5,
                                           10))
                         else
                          round(prat.imposta_da_2021)
                       end importo_riga_1,
                       case
                         when prat.anno < 2021 then
                          null
                         else
                          round(prat.tefa)
                       end importo_riga_2,
                       to_number(substr(f_f24_acc_tares(2,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_3,
                       to_number(substr(f_f24_acc_tares(3,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_4,
                       to_number(substr(f_f24_acc_tares(4,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_5,
                       to_number(substr(f_f24_acc_tares(5,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_6,
                       to_number(substr(f_f24_acc_tares(6,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_7,
                       to_number(substr(f_f24_acc_tares(7,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_8,
                       to_number(substr(f_f24_acc_tares(8,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_9,
                       to_number(substr(f_f24_acc_tares(9,
                                                        prat.importo_tari_tassa,
                                                        prat.interessi_tari_tassa,
                                                        prat.sanzioni_tari_tassa,
                                                        prat.importo_tariffa,
                                                        prat.interessi_tariffa,
                                                        prat.sanzioni_tariffa,
                                                        prat.maggiorazione,
                                                        prat.interessi_maggiorazione,
                                                        prat.sanzioni_maggiorazione),
                                        5,
                                        10)) importo_riga_10,
                       substr(f_f24_acc_tares(1,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_1,
                       case
                         when prat.anno < 2021 then
                          null
                         else
                          substr(f_f24_tari_tefa(1, null, null, prat.tefa), 1, 4)
                       end cotr_riga_2,
                       substr(f_f24_acc_tares(2,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_3,
                       substr(f_f24_acc_tares(3,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_4,
                       substr(f_f24_acc_tares(4,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_5,
                       substr(f_f24_acc_tares(5,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_6,
                       substr(f_f24_acc_tares(6,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_7,
                       substr(f_f24_acc_tares(7,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_8,
                       substr(f_f24_acc_tares(8,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_9,
                       substr(f_f24_acc_tares(9,
                                              prat.importo_tari_tassa,
                                              prat.interessi_tari_tassa,
                                              prat.sanzioni_tari_tassa,
                                              prat.importo_tariffa,
                                              prat.interessi_tariffa,
                                              prat.sanzioni_tariffa,
                                              prat.maggiorazione,
                                              prat.interessi_maggiorazione,
                                              prat.sanzioni_maggiorazione),
                              1,
                              4) cotr_riga_10,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(1,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_1,
                        case
                            when prat.anno < 2021 then
                                null
                            else
                            f_stampa_rateazione_f24(prat.tipo_tributo,
                                                    prat.anno,
                                                    substr(f_f24_tari_tefa(1, null, null, prat.tefa), 1, 4),
                                                    1,
                                                    1)
                        end rateaz_riga_2,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(2,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_3,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(3,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_4,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(4,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_5,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(5,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_6,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(6,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_7,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(7,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_8,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(8,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_9,
                        f_stampa_rateazione_f24(prat.tipo_tributo,
                                                prat.anno,
                                                substr(f_f24_acc_tares(9,
                                                                        prat.importo_tari_tassa,
                                                                        prat.interessi_tari_tassa,
                                                                        prat.sanzioni_tari_tassa,
                                                                        prat.importo_tariffa,
                                                                        prat.interessi_tariffa,
                                                                        prat.sanzioni_tariffa,
                                                                        prat.maggiorazione,
                                                                        prat.interessi_maggiorazione,
                                                                        prat.sanzioni_maggiorazione),
                                                        1,
                                                        4),
                                                1,
                                                1) rateaz_riga_10,
                       '' n_fab_riga_1,
                       '' n_fab_riga_2,
                       '' n_fab_riga_3,
                       '' detr,
                       '' acconto,
                       '' saldo,
                       ad4_comuni_c.sigla_cfis codice_comune,
                       decode(to_number(to_char(sysdate, 'yyyy')),
                              to_number(to_char(prat.anno, '9999')),
                              '',
                              'X') anno_imposta_diverso_solare,
                       f_primo_erede_cod_fiscale(soggetti.ni) cod_fiscale_erede,
                       'X' ravvedimento,
                       '' rateazione,
                       to_number(null) rate,
                       'RAVP' || to_char(prat.anno) || lpad(to_char(prat.pratica), 10, '0') identificativo_operazione
                  from ad4_comuni ad4_comuni_a,
                       ad4_provincie ad4_provincie_a,
                       archivio_vie,
                       soggetti,
                       contribuenti,
                       ad4_comuni ad4_comuni_b,
                       ad4_provincie ad4_provincie_b,
                       dati_generali dage,
                       ad4_comuni ad4_comuni_c,
	                   (select 
		                    prrv.num_fab_prat,
		                    (prrv.imposta_da_2021 + prrv.sanzioni_tari_tassa + prrv.interessi_tari_tassa)as imposta_da_2021,
		                    prrv.tefa as tefa,
		                    (prrv.importo_tari_tassa + prrv.sanzioni_tari_tassa + prrv.interessi_tari_tassa) as importo_tari_tassa,
		                    0 as interessi_tari_tassa,
		                    0 as sanzioni_tari_tassa,
		                    prrv.importo_tariffa,
		                    prrv.interessi_tariffa,
		                    prrv.sanzioni_tariffa,
		                    prrv.maggiorazione,
		                    prrv.interessi_maggiorazione,
		                    prrv.sanzioni_maggiorazione,
		                    prrv.cod_fiscale,
		                    prrv.maggiorazione_prat,
		                    prrv.pratica,
		                    prrv.anno,
		                    prrv.tipo_evento,
		                    prrv.tipo_tributo,
		                    prrv.numero
                        from
                           (select to_number(null) num_fab_prat,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3944',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              to_number(null),
                                              decode(sanz.flag_magg_tares,
                                                     'S',
                                                     0,
                                                     f_importo_f24_viol(sapr.importo,
                                                                        sapr.riduzione,
                                                                        0,
                                                                        prtr.tipo_tributo,
                                                                        prtr.anno,
                                                                        sanz.tipo_causale,
                                                                        sanz.flag_magg_tares)),
                                              0)) importo_tari_tassa,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3945',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) interessi_tari_tassa,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3946',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) sanzioni_tari_tassa,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3950',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) importo_tariffa,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3951',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) interessi_tariffa,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3952',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) sanzioni_tariffa,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3955',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              to_number(null),
                                              decode(sanz.flag_magg_tares,
                                                     'S',
                                                     f_importo_f24_viol(sapr.importo,
                                                                        sapr.riduzione,
                                                                        0,
                                                                        prtr.tipo_tributo,
                                                                        prtr.anno,
                                                                        sanz.tipo_causale,
                                                                        sanz.flag_magg_tares),
                                                     0),
                                              0)) maggiorazione,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3956',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) interessi_maggiorazione,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3957',
                                              f_importo_f24_viol(sapr.importo,
                                                                 sapr.riduzione,
                                                                 0,
                                                                 prtr.tipo_tributo,
                                                                 prtr.anno,
                                                                 sanz.tipo_causale,
                                                                 sanz.flag_magg_tares),
                                              0)) sanzioni_maggiorazione,
                                   sum(decode(sanz.cod_tributo_f24,
                                              '3944',
                                              f_importo_f24_viol_tefa(sapr.importo,
                                                                      sapr.riduzione,
                                                                      0,
                                                                      sapr.tipo_tributo,
                                                                      prtr.anno,
                                                                      sanz.tipo_causale,
                                                                      sanz.flag_magg_tares),
                                              0)) imposta_da_2021,
                                   sum(case
                                         when sanz.cod_tributo_f24 != '3944' or
                                              nvl(sanz.tipo_causale, '*') != 'E' or
                                              nvl(sanz.flag_magg_tares, '*') = 'S' then
                                          0
                                         else
                                          f_importo_f24_viol_tefa(sapr.importo,
                                                                  sapr.riduzione,
                                                                  0,
                                                                  'TEFA',
                                                                  prtr.anno,
                                                                  sanz.tipo_causale,
                                                                  sanz.flag_magg_tares)
                                       end) tefa,
                                   prtr.cod_fiscale,
                                   0 maggiorazione_prat,
                                   prtr.pratica,
                                   prtr.anno,
                                   prtr.tipo_evento,
                                   prtr.tipo_tributo,
                                   prtr.numero
                              from pratiche_tributo prtr, sanzioni_pratica sapr, sanzioni sanz
                             where prtr.tipo_pratica = 'V'
                               and sapr.pratica = prtr.pratica
                               and sapr.cod_sanzione = sanz.cod_sanzione
                               and sapr.sequenza_sanz = sanz.sequenza
                               and sapr.tipo_tributo = sanz.tipo_tributo
                               and prtr.pratica = :pPratica
                             group by prtr.pratica,
                                      prtr.cod_fiscale,
                                      prtr.anno,
                                      prtr.tipo_evento,
                                      prtr.tipo_tributo,
                                      prtr.numero) prrv
                        ) prat
                 where ad4_comuni_a.provincia_stato = ad4_provincie_a.provincia(+)
                   and soggetti.cod_pro_res = ad4_comuni_a.provincia_stato(+)
                   and soggetti.cod_com_res = ad4_comuni_a.comune(+)
                   and soggetti.cod_via = archivio_vie.cod_via(+)
                   and ad4_comuni_b.provincia_stato = ad4_provincie_b.provincia(+)
                   and soggetti.cod_pro_nas = ad4_comuni_b.provincia_stato(+)
                   and soggetti.cod_com_nas = ad4_comuni_b.comune(+)
                   and soggetti.cod_via = archivio_vie.cod_via(+)
                   and dage.pro_cliente = ad4_comuni_c.provincia_stato
                   and dage.com_cliente = ad4_comuni_c.comune
                   and contribuenti.ni = soggetti.ni
                   and prat.cod_fiscale = contribuenti.cod_fiscale
                   and prat.pratica = :pPratica
                   and :pCodFiscale = :pCodFiscale
                   and (prat.importo_tari_tassa > 0.49 or prat.interessi_tari_tassa > 0.49 or
                    prat.sanzioni_tari_tassa > 0.49 or prat.importo_tariffa > 0.49 or
                    prat.interessi_tariffa > 0.49 or prat.sanzioni_tariffa > 0.49 or
                    prat.maggiorazione > 0.49 or prat.interessi_maggiorazione > 0.49 or
                    prat.sanzioni_maggiorazione > 0.49)
                    order by 1, 2
    """
    }
}
