package it.finmatica.tr4.contribuenti.f24query

class F24ViolazioniTASIQuery {

    static def query() {
        return """
select 'TASI' AS tributo,
       contribuenti.cod_fiscale,
       translate(soggetti.cognome_nome, '/', ' ') csoggnome,
       decode(soggetti.cod_via,
              null,
              soggetti.denominazione_via,
              archivio_vie.denom_uff) ind,
       soggetti.num_civ num_civ,
       soggetti.suffisso suff,
       decode(soggetti.cod_via,
              null,
              soggetti.denominazione_via,
              archivio_vie.denom_uff) ||
       decode(soggetti.num_civ, null, '', ', ' || soggetti.num_civ) ||
       decode(soggetti.suffisso, null, '', '/' || soggetti.suffisso) indirizzo_dich,
       ad4_comuni_a.denominazione comune,
       ad4_provincie_a.sigla provincia,
       ad4_comuni_b.denominazione comune_nas,
       ad4_provincie_b.sigla provincia_nas,
       soggetti.sesso sesso,
       soggetti.cognome cognome,
       soggetti.nome nome,
       to_char(soggetti.data_nas, 'yyyy') anno_nascita,
       to_char(soggetti.data_nas, 'mm') mese_nascita,
       to_char(soggetti.data_nas, 'dd') giorno_nascita,
       to_char(tasi.anno, '9999') anno,
       to_number(substr(f_f24_tasi(1,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_1,
       to_number(substr(f_f24_tasi(2,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_2,
       to_number(substr(f_f24_tasi(3,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_3,
       to_number(substr(f_f24_tasi(4,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_4,
       to_number(substr(f_f24_tasi(5,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_5,
       to_number(substr(f_f24_tasi(6,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_6,
       to_number(substr(f_f24_tasi(7,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_7,
       to_number(substr(f_f24_tasi(8,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_8,
       to_number(substr(f_f24_tasi(9,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(importo, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_9,
       to_number(substr(f_f24_tasi(10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(importo, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_10,
       substr(f_f24_tasi(1,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_1,
       substr(f_f24_tasi(2,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_2,
       substr(f_f24_tasi(3,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_3,
       substr(f_f24_tasi(4,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_4,
       substr(f_f24_tasi(5,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_5,
       substr(f_f24_tasi(6,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_6,
       substr(f_f24_tasi(7,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_7,
       substr(f_f24_tasi(8,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_8,
       substr(f_f24_tasi(9,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_9,
       substr(f_f24_tasi(10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_10,
       substr(f_f24_tasi(1,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_1,
       substr(f_f24_tasi(2,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_2,
       substr(f_f24_tasi(3,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_3,
       substr(f_f24_tasi(4,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_4,
       substr(f_f24_tasi(5,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_5,
       substr(f_f24_tasi(6,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_6,
       substr(f_f24_tasi(7,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_7,
       substr(f_f24_tasi(8,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_8,
       substr(f_f24_tasi(9,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_9,
       substr(f_f24_tasi(10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_10,
       translate(to_char(tasi.detr, '999,999,990.00'), ',.', '.,') detr,
       'X' acconto,
       'X' saldo,
       ad4_comuni_c.sigla_cfis codice_comune,
       decode(to_number(to_char(sysdate, 'yyyy')),
              to_number(to_char(tasi.anno, '9999')),
              '',
              'X') anno_imposta_diverso_solare,
       f_primo_erede_cod_fiscale(soggetti.ni) cod_fiscale_erede,
       decode(tasi.tipo_pratica,
              'L',
              'LIQP',
              'A',
              'ACC' || decode(tasi.tipo_evento, 'T', 'T', 'P')) ||
       to_char(tasi.anno) || lpad(to_char(tasi.pratica), 10, '0') identificativo_operazione
  from ad4_comuni ad4_comuni_a,
       ad4_provincie ad4_provincie_a,
       archivio_vie,
       soggetti,
       contribuenti,
       ad4_comuni ad4_comuni_b,
       ad4_provincie ad4_provincie_b,
       dati_generali dage,
       ad4_comuni ad4_comuni_c,
       (select max(prtr.cod_fiscale) cod_fiscale,
               max(vdog.num_fabbricati_ab_tasi) num_fabb_ab,
               max(vdog.num_fabbricati_rurali_tasi) num_fabb_rurali,
               max(vdog.num_fabbricati_altri_tasi) num_fabb_altri,
               to_number(null) num_fabb_d,
               sum(round(decode(sanz.tipo_causale, 'E', sapr.importo, 0))) imposta,
               sum(round(decode(sapr.cod_sanzione,
                                98,
                                0,
                                99,
                                0,
                                198,
                                0,
                                199,
                                0,
                                sapr.importo) *
                         (100 - decode(:pImportoRidotto,
                                       'S',
                                       nvl(sapr.riduzione, 0),
                                       0)) / 100,
                         2)) importo,
               sum(decode(sapr.cod_sanzione,
                          98,
                          sapr.importo,
                          99,
                          sapr.importo,
                          198,
                          sapr.importo,
                          199,
                          sapr.importo,
                          0)) interessi,
               sum(round(decode(sapr.cod_sanzione,
                                1,
                                0,
                                21,
                                0,
                                24,
                                0,
                                31,
                                0,
                                101,
                                0,
                                121,
                                0,
                                124,
                                0,
                                131,
                                0,
                                98,
                                0,
                                99,
                                0,
                                198,
                                0,
                                199,
                                0,
                                sapr.importo) *
                         (100 - decode(:pImportoRidotto,
                                       'S',
                                       nvl(sapr.riduzione, 0),
                                       0)) / 100,
                         2)) sanzioni,
               max(prtr.anno) anno,
               to_number(null) detr,
               prtr.pratica,
               max(prtr.tipo_pratica) tipo_pratica,
               max(prtr.tipo_evento) tipo_evento
          from pratiche_tributo         prtr,
               sanzioni_pratica         sapr,
               sanzioni                 sanz,
               violazioni_dettagli_ogim vdog
         where prtr.pratica = sapr.pratica(+)
           and prtr.tipo_tributo = sanz.tipo_tributo
           and sapr.cod_sanzione = sanz.cod_sanzione
           and sapr.sequenza_sanz = sanz.sequenza
           and prtr.pratica = vdog.pratica(+)
           and prtr.pratica = :pPratica
         group by prtr.pratica) tasi
 where ad4_comuni_a.provincia_stato = ad4_provincie_a.provincia(+)
   and soggetti.cod_pro_res = ad4_comuni_a.provincia_stato(+)
   and soggetti.cod_com_res = ad4_comuni_a.comune(+)
   and soggetti.cod_via = archivio_vie.cod_via(+)
   and ad4_comuni_b.provincia_stato = ad4_provincie_b.provincia(+)
   and soggetti.cod_pro_nas = ad4_comuni_b.provincia_stato(+)
   and soggetti.cod_com_nas = ad4_comuni_b.comune(+)
   and soggetti.cod_via = archivio_vie.cod_via(+)
   and dage.pro_cliente = ad4_comuni_c.provincia_stato
   and dage.com_cliente = ad4_comuni_c.comune
   and contribuenti.ni = soggetti.ni
   and contribuenti.cod_fiscale = tasi.cod_fiscale
   """ +
                """
union all
select 'TASI' AS tributo,
       contribuenti.cod_fiscale,
       translate(soggetti.cognome_nome, '/', ' ') csoggnome,
       decode(soggetti.cod_via,
              null,
              soggetti.denominazione_via,
              archivio_vie.denom_uff) ind,
       soggetti.num_civ num_civ,
       soggetti.suffisso suff,
       decode(soggetti.cod_via,
              null,
              soggetti.denominazione_via,
              archivio_vie.denom_uff) ||
       decode(soggetti.num_civ, null, '', ', ' || soggetti.num_civ) ||
       decode(soggetti.suffisso, null, '', '/' || soggetti.suffisso) indirizzo_dich,
       ad4_comuni_a.denominazione comune,
       ad4_provincie_a.sigla provincia,
       ad4_comuni_b.denominazione comune_nas,
       ad4_provincie_b.sigla provincia_nas,
       soggetti.sesso sesso,
       soggetti.cognome cognome,
       soggetti.nome nome,
       to_char(soggetti.data_nas, 'yyyy') anno_nascita,
       to_char(soggetti.data_nas, 'mm') mese_nascita,
       to_char(soggetti.data_nas, 'dd') giorno_nascita,
       to_char(tasi.anno, '9999') anno,
       to_number(substr(f_f24_tasi(1 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_1,
       to_number(substr(f_f24_tasi(2 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_2,
       to_number(substr(f_f24_tasi(3 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_3,
       to_number(substr(f_f24_tasi(4 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_4,
       to_number(substr(f_f24_tasi(5 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_5,
       to_number(substr(f_f24_tasi(6 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_6,
       to_number(substr(f_f24_tasi(7 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_7,
       to_number(substr(f_f24_tasi(8 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_8,
       to_number(substr(f_f24_tasi(9 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_9,
       to_number(substr(f_f24_tasi(10 + 10,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   null,
                                   tasi.imposta,
                                   null,
                                   tasi.num_fabb_ab,
                                   tasi.num_fabb_rurali,
                                   tasi.num_fabb_altri,
                                   null,
                                   null,
                                   tasi.num_fabb_d,
                                   nvl(tasi.sanzioni, 0),
                                   tasi.interessi),
                        5,
                        10)) importo_riga_10,
       substr(f_f24_tasi(1 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_1,
       substr(f_f24_tasi(2 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_2,
       substr(f_f24_tasi(3 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_3,
       substr(f_f24_tasi(4 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_4,
       substr(f_f24_tasi(5 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_5,
       substr(f_f24_tasi(6 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_6,
       substr(f_f24_tasi(7 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_7,
       substr(f_f24_tasi(8 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_8,
       substr(f_f24_tasi(9 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_9,
       substr(f_f24_tasi(10 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              1,
              4) cotr_riga_10,
       substr(f_f24_tasi(1 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_1,
       substr(f_f24_tasi(2 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_2,
       substr(f_f24_tasi(3 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_3,
       substr(f_f24_tasi(4 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         tasi.num_fabb_ab + tasi.num_fabb_rurali + tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_4,
       substr(f_f24_tasi(5 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_5,
       substr(f_f24_tasi(6 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_6,
       substr(f_f24_tasi(7 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_7,
       substr(f_f24_tasi(8 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_8,
       substr(f_f24_tasi(9 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_9,
       substr(f_f24_tasi(10 + 10,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         tasi.imposta,
                         null,
                         tasi.num_fabb_ab,
                         tasi.num_fabb_rurali,
                         tasi.num_fabb_altri,
                         null,
                         null,
                         tasi.num_fabb_d,
                         nvl(tasi.sanzioni, 0),
                         tasi.interessi),
              15,
              4) n_fab_riga_10,
       translate(to_char(tasi.detr, '999,999,990.00'), ',.', '.,') detr,
       'X' acconto,
       'X' saldo,
       ad4_comuni_c.sigla_cfis codice_comune,
       decode(to_number(to_char(sysdate, 'yyyy')),
              to_number(to_char(tasi.anno, '9999')),
              '',
              'X') anno_imposta_diverso_solare,
       f_primo_erede_cod_fiscale(soggetti.ni) cod_fiscale_erede,
       decode(tasi.tipo_pratica,
              'L',
              'LIQP',
              'A',
              'ACC' || decode(tasi.tipo_evento, 'T', 'T', 'P')) ||
       to_char(tasi.anno) || lpad(to_char(tasi.pratica), 10, '0') identificativo_operazione
  from ad4_comuni ad4_comuni_a,
       ad4_provincie ad4_provincie_a,
       archivio_vie,
       soggetti,
       contribuenti,
       ad4_comuni ad4_comuni_b,
       ad4_provincie ad4_provincie_b,
       dati_generali dage,
       ad4_comuni ad4_comuni_c,
       (select max(prtr.cod_fiscale) cod_fiscale,
               max(vdog.num_fabbricati_ab_tasi) num_fabb_ab,
               max(vdog.num_fabbricati_rurali_tasi) num_fabb_rurali,
               max(vdog.num_fabbricati_altri_tasi) num_fabb_altri,
               to_number(null) num_fabb_d,
               sum(round(decode(sanz.tipo_causale, 'E', sapr.importo, 0))) imposta,
               sum(round(decode(sapr.cod_sanzione,
                                98,
                                0,
                                99,
                                0,
                                198,
                                0,
                                199,
                                0,
                                sapr.importo) *
                         (100 - decode(:pImportoRidotto,
                                       'S',
                                       nvl(sapr.riduzione, 0),
                                       0)) / 100,
                         2)) importo,
               sum(decode(sapr.cod_sanzione,
                          98,
                          sapr.importo,
                          99,
                          sapr.importo,
                          198,
                          sapr.importo,
                          199,
                          sapr.importo,
                          0)) interessi,
               sum(round(decode(sapr.cod_sanzione,
                                1,
                                0,
                                21,
                                0,
                                24,
                                0,
                                31,
                                0,
                                101,
                                0,
                                121,
                                0,
                                124,
                                0,
                                131,
                                0,
                                98,
                                0,
                                99,
                                0,
                                198,
                                0,
                                199,
                                0,
                                sapr.importo) *
                         (100 - decode(:pImportoRidotto,
                                       'S',
                                       nvl(sapr.riduzione, 0),
                                       0)) / 100,
                         2)) sanzioni,
               max(prtr.anno) anno,
               to_number(null) detr,
               prtr.pratica,
               max(prtr.tipo_pratica) tipo_pratica,
               max(prtr.tipo_evento) tipo_evento
          from pratiche_tributo         prtr,
               sanzioni_pratica         sapr,
               sanzioni                 sanz,
               violazioni_dettagli_ogim vdog
         where prtr.pratica = sapr.pratica(+)
           and prtr.tipo_tributo = sanz.tipo_tributo
           and sapr.cod_sanzione = sanz.cod_sanzione
           and sapr.sequenza_sanz = sanz.sequenza
           and prtr.pratica = vdog.pratica(+)
           and prtr.pratica = :pPratica
         group by prtr.pratica) tasi
 where ad4_comuni_a.provincia_stato = ad4_provincie_a.provincia(+)
   and soggetti.cod_pro_res = ad4_comuni_a.provincia_stato(+)
   and soggetti.cod_com_res = ad4_comuni_a.comune(+)
   and soggetti.cod_via = archivio_vie.cod_via(+)
   and ad4_comuni_b.provincia_stato = ad4_provincie_b.provincia(+)
   and soggetti.cod_pro_nas = ad4_comuni_b.provincia_stato(+)
   and soggetti.cod_com_nas = ad4_comuni_b.comune(+)
   and soggetti.cod_via = archivio_vie.cod_via(+)
   and dage.pro_cliente = ad4_comuni_c.provincia_stato
   and dage.com_cliente = ad4_comuni_c.comune
   and contribuenti.ni = soggetti.ni
   and contribuenti.cod_fiscale = tasi.cod_fiscale
   and f_f24_tasi(11,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  tasi.num_fabb_ab,
                  tasi.num_fabb_rurali,
                  tasi.num_fabb_altri,
                  null,
                  null,
                  tasi.num_fabb_d,
                  nvl(tasi.sanzioni, 0),
                  tasi.interessi) is not null

        """
    }

}
