--liquibase formatted sql
--changeset abrandolini:20250408_094738_anadce_ins stripComments:false context:"TRT2 or TRV4"
--validCheckSum: 1:any

Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 40, 'CANCELLAZIONE PER MANCATO RINNOVO DI PS', 2, 60,
     'C', 'S', 'M', 'Canc. Per Mancato Rinnovo Ps', 6,
     'S', 'A', 'S', '2', 4,
     'MANCATO RINNOVO PS', 'CMR', 'CANC. PER MANCATO RINNOVO PS', 'CANC. PER MANCATO RINNOVO PS');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO, MOTIVO_PSE,
 MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 41, 'CANCELLAZIONE SU ISTANZA D''UFFICIO', 2, 59,
     'C', 'S', 'U', 'Cancellazione D''Ufficio', 5,
     'S', 'A', 'S', '2', 4,
     'D''UFFICIO', 'S', 60, 18, 18,
     18, 'CUF', 'CANC. D''UFFICIO', 'CANC. D''UFFICIO');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO, MOTIVO_PSE,
 MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 42, 'DOPPIA ISCRIZIONE', 2, 58,
     'C', 'S', 'D', 'Doppia Iscrizione', 4,
     'S', 'A', 'S', '2', 4,
     'DOPPIA ISCRIZIONE', 'S', 80, 18, 18,
     18, 'DOP', 'CANC. PER DOPPIA ISCRIZIONE', 'CANC. PER DOPPIA ISCRIZIONE');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR,
 SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 43, 'EMIGRAZIONE', 2, 51,
     'C', 'S', 'E', 'Emigrazione', 1,
     'S', 'M', 'S', '1', 1,
     'S', 15, 15, 15, 15,
     'EMI', 'EMIGRATO', 'EMIGRATA');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, COD_VARIAZIONE, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR,
 SEQ_EVENTO_TPR, FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4,
 PROVVEDIMENTO_APR4, FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO, MOTIVO_PSE,
 MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 45, 'IRREPERIBILITA'' AL CENSIMENTO', 2, 53,
     'C', 'C', 'S', 'C', 'Irreperibilita'' al Censimento',
     3, 'S', 'I', 'S', '2',
     2, 'S', 11, 11, 11,
     11, 'IRR', 'IRREPERIBILE', 'IRREPERIBILE');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR,
 SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 46, 'IRREPERIBILITA'' ACCERTATA', 2, 53,
     'C', 'S', 'I', 'Irreperibilita''', 2,
     'S', 'I', 'S', '2', 3,
     'S', 11, 11, 11, 11,
     'IRR', 'IRREPERIBILE', 'IRREPERIBILE');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO, MOTIVO_PSE,
 MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 49, 'MORTE', 2, 50,
     'C', 'S', 'X', 'Morte', 8,
     'S', 'N', 'S', '2', 4,
     'MORTE', 'S', 12, 12, 12,
     12, 'MOR', 'DECEDUTO', 'DECEDUTA');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 FLAG_ELE, MOTIVO_ELE, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 67, 'EMIGRAZIONE A.I.R.E.', 3, 52,
     'C', 'S', 'A', 'Emigrazione AIRE', 7,
     'S', 'M', 'S', '2', 1,
     'S', 9, 'AIR', 'ISCRITTO A.I.R.E.', 'ISCRITTA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, COD_VARIAZIONE, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR,
 SEQ_EVENTO_TPR, FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4,
 PROVVEDIMENTO_APR4, MOTIVO_APR4, FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO,
 MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 98, 'MORTE ESTERO', 2, 50,
     'C', 'E', 'S', 'Y', 'Morte all''Estero',
     9, 'S', 'N', 'S', '2',
     4, 'MORTE ESTERO', 'S', 12, 12,
     12, 12, 'MOR', 'DECEDUTO', 'DECEDUTA');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, RICHIESTA_APR4,
 PROVVEDIMENTO_APR4, MOTIVO_APR4, FLAG_ELE, MOTIVO_ELE, MOTIVO_GPO,
 MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 99, 'TRASFERIMENTO IN ALTRO COMUNE ITALIANO', 2, 61,
     'C', 'S', 'T', 'Trasf. Altro Comune Italiano', 8,
     'S', 'A', 'S', '1', 1,
     4, 'TRASF.ALTRO COMUNE ITA', 'S', 15, 15,
     15, 15, 'TCI', 'TRASFERITO IN ALTRO COMUNE', 'TRASFERITA IN ALTRO COMUNE');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_ELE, MOTIVO_ELE)
Values
    ('RES', 102, 'CANCELLAZIONE PER ACCERTAMENTI NEGATIVI', 2, 62,
     'C', 'S', 31);
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, COD_VARIAZIONE, FLAG_ELE, MOTIVO_ELE)
Values
    ('RES', 117, 'CANC. X ACCERTAMENTI NEGATIVI - DA AIRE', 2, 62,
     'C', 'A', 'S', 9);
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 128, 'CANC. PER REVOCA MISURE ACCOGLIENZA', 2, 63,
     'C', 'S', 'R', 'Revoca Misure Accoglienza', 10,
     'S', 'I', 'S', '2', 4,
     'REVOCA MISURE', 'RMA', 'CANC. PER REVOCA MISURE', 'CANC. PER REVOCA MISURE');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, SIGLA_VANA, DESCRIZIONE_M, DESCRIZIONE_F)
Values
    ('RES', 129, 'CANC. PER ALLONTAMENTO NON GIUSTIFICATO', 2, 64,
     'C', 'S', 'G', 'Allontamanento Non Giustif.', 11,
     'S', 'I', 'S', '2', 4,
     'ALLONTANAMENTO', 'ANG', 'CANC. PER ALLONTANAMENTO', 'CANC. PER ALLONTANAMENTO');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_ISTAT, TIPO_EVENTO_ISTAT, FLAG_APR4, TIPO_RICHIESTA_APR4, PROVVEDIMENTO_APR4,
 MOTIVO_APR4, SIGLA_VANA)
Values
    ('RES', 137, 'CANC. PER MANCATO RINNOVO DIMORA', 2, 65,
     'C', 'S', 'N', 'Mancato Rinnovo Dimora', 12,
     'S', 'I', 'S', '2', 4,
     'MANCATO RINNOVO DIMORA', 'MRD');
-- A.i.r.e.
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 14, 'CANCELLAZIONE D''UFFICIO', 4, 59,
     'C', 'S', 'U', 'Cancellazione d''Ufficio', 6,
     'S', 'S', 'E04', 'S', 16,
     19, 19, 19, 'CUF', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 15, 'DOPPIA ISCRIZIONE', 4, 58,
     'C', 'S', 'D', 'Doppia Iscrizione', 5,
     'S', 'S', 'E04', 'S', 16,
     19, 19, 19, 'DOP', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 17, 'IMMIGRAZIONE IN ALTRO COMUNE', 4, 55,
     'C', 'S', 'I', 'Immigrazione in altro Comune', 1,
     'S', 'S', 'E01', 'S', 16,
     19, 19, 19, 'IMC', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 18, 'IRREPERIBILITA'' PRESUNTA', 4, 54,
     'C', 'S', 'P', 'Irreperibilità Presunta', 2,
     'S', 'S', 'E04', 'S', 11,
     11, 11, 11, 'IRP', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 21, 'MORTE', 4, 50,
     'C', 'S', 'X', 'Morte', 7,
     'S', 'S', 'E02', 'S', 12,
     12, 12, 12, 'MOR', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 23, 'PERDITA CITTADINANZA ITALIANA', 4, 57,
     'C', 'S', 'C', 'Perdita Citt. Italiana', 3,
     'S', 'S', 'E05', 'S', 13,
     19, 19, 19, 'PCI', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_TPR, TIPO_EVENTO_TPR, DES_EVENTO_TPR, SEQ_EVENTO_TPR,
 FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, FLAG_ELE, MOTIVO_ELE,
 MOTIVO_GPO, MOTIVO_PSE, MOTIVO_SCR, SIGLA_VANA, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 32, 'TRASFERIMENTO AIRE IN ALTRO C.', 4, 56,
     'C', 'S', 'T', 'Trasf. AIRE in altro Comune', 4,
     'S', 'S', 'E03', 'S', 16,
     19, 19, 19, 'TAC', 'CANCELLATO A.I.R.E.',
     'CANCELLATA A.I.R.E.');
Insert into ANADCE
(ANAGRAFE, CODICE, DESCRIZIONE, COD_MOV, COD_EVE,
 TIPO_EVENTO, FLAG_R01, FLAG_AIRE01, MOTIVO_AIRE01, DESCRIZIONE_M,
 DESCRIZIONE_F)
Values
    ('AIR', 36, 'REIMMIGRAZIONE DA A.I.R.E.', 1, 4,
     'C', 'S', 'S', 'E01', 'RESIDENTE',
     'RESIDENTE');
