--liquibase formatted sql
--changeset dmarotta:20250326_152438_anadrp_ins stripComments:false context:"TRT2 or TRV4"
--validCheckSum: 1:any

ALTER TABLE anadrp DISABLE ALL TRIGGERS;

INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CC', 'M', 1, 'Capo Convivente');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CC', 'F', 1, 'Capo Convivente');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CF', 'M', 1, 'I.S.');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CF', 'F', 1, 'I.S.');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'MG', 'F', 2, 'Moglie');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'MR', 'M', 2, 'Marito');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'FG', 'M', 3, 'Figlio');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'FG', 'F', 3, 'Figlia');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AF', 'M', 4, 'Affiliato');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AF', 'F', 4, 'Affiliata');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AD', 'M', 5, 'Adottato');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AD', 'F', 5, 'Adottata');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'MD', 'F', 6, 'Madre');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'PD', 'M', 6, 'Padre');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'FR', 'M', 7, 'Fratello');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'SR', 'F', 7, 'Sorella');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AV', 'M', 8, 'Avo');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AV', 'F', 8, 'Ava');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NP', 'M', 9, 'Nipote');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NP', 'F', 9, 'Nipote');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'ZI', 'M', 10, 'Zio');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'ZI', 'F', 10, 'Zia');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CU', 'M', 11, 'Cugino');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CU', 'F', 11, 'Cugina');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'FS', 'M', 12, 'Figliastro');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'FS', 'F', 12, 'Figliastra');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'GE', 'M', 13, 'Genero');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NU', 'F', 13, 'Nuora');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'SC', 'M', 14, 'Suocero');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'SC', 'F', 14, 'Suocera');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CT', 'M', 15, 'Cognato');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CT', 'F', 15, 'Cognata');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'MN', 'F', 16, 'Matrigna');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'PN', 'M', 16, 'Patrigno');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'FT', 'M', 17, 'Fratellastro');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'ST', 'F', 17, 'Sorellastra');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'IC', 'M', 18, 'In Convivenza');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'IC', 'F', 18, 'In Convivenza');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CV', 'M', 19, 'Convivente');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'CV', 'F', 19, 'Convivente');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'PE', 'M', 20, 'Pronipote');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'PE', 'F', 20, 'Pronipote');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NC', 'M', 21, 'Nipote Collaterale');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NC', 'F', 21, 'Nipote Collaterale');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'PC', 'M', 22, 'Pronipote Collaterale');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'PC', 'F', 22, 'Pronipote Collaterale');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AE', 'M', 23, 'Affiliante');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AE', 'F', 23, 'Affiliante');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'DM', 'M', 24, 'Domestico');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'DM', 'F', 24, 'Domestica');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AP', 'M', 25, 'Affidato in preadozione');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AP', 'F', 25, 'Affidata in preadozione');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AG', 'M', 26, 'Aggregato');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AG', 'F', 26, 'Aggregata');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AN', 'M', 27, 'Affine');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'AN', 'F', 27, 'Affine');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NN', 'M', 28, 'Nonno');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'NN', 'F', 28, 'Nonna');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'BN', 'M', 29, 'Bisnonno');
INSERT INTO anadrp ( COD_RP, SESSO, SEQUENZA, DESCRIZIONE)
VALUES ( 'BN', 'F', 29, 'Bisnonna');

ALTER TABLE anadrp ENABLE ALL TRIGGERS;
