--liquibase formatted sql
--changeset dmarotta:20250326_152438_anadev_ins stripComments:false context:"TRT2 or TRV4"
--validCheckSum: 1:any

INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 1,'NASCITA',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=1);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 2,'IMMIGRAZIONE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=2);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 3,'REIMMIGRAZIONE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=3);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 4,'REIMMIGRAZIONE DA AIRE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=4);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 5,'ISCRIZIONE D''UFFICIO',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=5);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 6,'ISCRIZIONE D''UFFICIO AIRE',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=6);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 7,'TRASFERIMENTO AIRE DA ALTRO C.',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=7);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 8,'ACQUISTO CITTADINANZA ITALIANA',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=8);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 9,'REISCRIZIONE DA IRREPERIB.',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=9);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 10,'RESIDENZA ALL''ESTERO',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=10);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 11,'REISCR. DA MANCATO RINNOVO PS',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=11);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 50,'MORTE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=50);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 51,'EMIGRAZIONE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=51);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 52,'EMIGRAZIONE AIRE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=52);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 53,'IRREPERIBILITA''',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=53);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 54,'IRREPERIBILITA'' PRESUNTA',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=54);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 55,'IMMIGRAZIONE IN ALTRO COMUNE',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=55);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 56,'TRASFERIMENTO AIRE IN ALTRO C.',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=56);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 57,'PERDITA CITTADINANZA ITALIANA',1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=57);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 58,'DOPPIA ISCRIZIONE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=58);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 59,'CANCELLAZIONE D''UFFICIO',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=59);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 60,'CANC. PER MANCATO RINNOVO PS',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=60);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 70,'IN ATTESA DI ISCRIZIONE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=70);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 71,'IMMIGRAZIONE ANNULLATA',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=71);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 80,'NON RESIDENTE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=80);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 90,'VARIAZIONE RAPPORTO PARENTELA',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=90);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 91,'TRASFERIMENTO RESIDENZA',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=91);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 92,'SCISSIONE',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=92);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 93,'MATRIMONIO',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=93);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 94,'VEDOVANZA',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=94);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 97,'RETTIFICA DATI MATRIMONIO',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=97);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 98,'RETTIFICA INDIRIZZO',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=98);
INSERT INTO anadev ( COD_EV, DESCRIZIONE, SEGNALAZIONE) SELECT 99,'RETTIFICA',0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM anadev WHERE COD_EV=99);
