--liquibase formatted sql 
--changeset rvattolo:20250715_171619_77694_4_ins_sanzioni stripComments:false runOnChange:true 

-- 
--	77694/78175 : Inserimento sanzioni 
-- 	  N° 04 : Evasa, Omessa, Tardivo
--            SALTO/TOTALE (6xx)
--
DECLARE
  w_tipo_tributo  varchar2(5);
  --
  w_cod_sanzione  number;
  w_sequenza     number;
  --
----------------------------------------
function check_tipo_tributo(
  a_tipo_tributo in VARCHAR2
  ) return number
IS
  --
  w_contatore             number;
  --
begin
  select count(*)
    into w_contatore
    from tipi_tributo
   where tipo_tributo = a_tipo_tributo;
  --   
  if w_contatore = 0 then
    dbms_output.put_line ('Tipo tributo '||a_tipo_tributo||' non configurato.');
  else
    dbms_output.put_line ('Tipo tributo '||a_tipo_tributo||' configurato.');
  end if;
  --   
  return w_contatore;
end check_tipo_tributo;
----------------------------------------
function check_sanzione(
  a_tipo_tributo in VARCHAR2,
  a_cod_sanzione number,
  a_sequenza number
  ) return number
IS
  --
  w_contatore             number;
  --
begin
  select count(*)
    into w_contatore
    from sanzioni
   where tipo_tributo = a_tipo_tributo
     and cod_sanzione = a_cod_sanzione
     and sequenza = a_sequenza;
  --   
  if w_contatore = 0 then
    dbms_output.put_line ('Sanzione '||a_tipo_tributo||'/'||a_cod_sanzione||'-'||a_sequenza||' non configurato.');
  else
    dbms_output.put_line ('Sanzione '||a_tipo_tributo||'/'||a_cod_sanzione||'-'||a_sequenza||' già configurato.');
  end if;
  --   
  return w_contatore;
end check_sanzione;
----------------------------------------
BEGIN
  --
  w_tipo_tributo := 'TARSU';
  --
  if(check_tipo_tributo(w_tipo_tributo) > 0) then
  
	-- SALDO/TOTALE -------------------------------------------------
	
    w_cod_sanzione := 655;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE PRIMA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 1, 'S', '3944', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 655;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE PRIMA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 1, 'S', '3944', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 656;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE PRIMA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 1, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 656;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE PRIMA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 1, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 657;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE PRIMA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 1, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 657;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE PRIMA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 1, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 658;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE PRIMA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 1, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 658;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE PRIMA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 1, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 659;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) PRIMA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 1, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 659;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) PRIMA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 1, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 665;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE SECONDA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 2, 'S', '3944', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 665;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE SECONDA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 2, 'S', '3944', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 666;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE SECONDA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 2, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 666;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE SECONDA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 2, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 667;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE SECONDA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 2, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 667;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE SECONDA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 2, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 668;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE SECONDA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 2, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 668;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE SECONDA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 2, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 669;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) SECONDA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 2, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 669;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) SECONDA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 2, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 675;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE TERZA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 3, 'S', '3944', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 675;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE TERZA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 3, 'S', '3944', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 676;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE TERZA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 3, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 676;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE TERZA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 3, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 677;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE TERZA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 3, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 677;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE TERZA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 3, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 678;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE TERZA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 3, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 678;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE TERZA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 3, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 679;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) TERZA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 3, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 679;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) TERZA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 3, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 685;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE QUARTA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 4, 'S', '3944', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 685;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'COMPONENTI PEREQUATIVE EVASE SALDO/TOTALE QUARTA RATA', NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL,
			434, 'S', NULL, 2, 'E', 4, 'S', '3944', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 686;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE QUARTA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 4, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 686;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'OMESSO VERSAMENTO C.PEREQ. SALDO/TOTALE QUARTA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'O', 4, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 687;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE QUARTA RATA', 30, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 4, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 687;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'PARZIALE VERSAMENTO C.PEREQ. SALDO/TOTALE QUARTA RATA', 25, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'P', 4, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 688;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE QUARTA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 4, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 688;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARDIVO VERSAMENTO C.PEREQ. SALDO/TOTALE QUARTA RATA', 100, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'T', 4, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 689;
    w_sequenza := 1;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) QUARTA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 4, 'S', '3946', NULL,
	TO_DATE('01/01/1900','dd/MM/YYYY'),TO_DATE('31/08/2024','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

    w_cod_sanzione := 689;
    w_sequenza := 2;
	if(check_sanzione(w_tipo_tributo,w_cod_sanzione,w_sequenza) < 1) then

	INSERT INTO SANZIONI
			(TIPO_TRIBUTO,COD_SANZIONE,SEQUENZA,DESCRIZIONE,PERCENTUALE,SANZIONE,SANZIONE_MINIMA,RIDUZIONE,
			 FLAG_IMPOSTA,FLAG_INTERESSI,FLAG_PENA_PECUNIARIA,GRUPPO_SANZIONE,TRIBUTO,FLAG_CALCOLO_INTERESSI,RIDUZIONE_2,
			 TIPOLOGIA_RUOLO,TIPO_CAUSALE,RATA,FLAG_MAGG_TARES,COD_TRIBUTO_F24,TIPO_VERSAMENTO,
			 DATA_INIZIO,DATA_FINE,UTENTE,DATA_VARIAZIONE,NOTE)
	values (w_tipo_tributo,w_cod_sanzione,w_sequenza,'TARD.VERS. C.PEREQ. SALDO/TOTALE (ENTRO 30 GG) QUARTA RATA', 50, NULL, NULL, NULL, NULL, NULL, 'S', NULL,
			423, NULL, NULL, 2, 'TP30', 4, 'S', '3946', NULL,
	TO_DATE('01/09/2024','dd/MM/YYYY'),TO_DATE('31/12/9999','dd/MM/YYYY'),'#TR4',sysdate,null);

	end if;

	commit;
	
  end if;
END;
/
