--liquibase formatted sql 
--changeset abrandolini:20250326_152401_liquidazione_ogpr_acc stripComments:false runOnChange:true 
 
create or replace force view liquidazione_ogpr_acc as
select OGPR.OGGETTO_PRATICA OGGETTO_PRATICA_LIQ
   , OGPR.VALORE VALORE_LIQ
   , OGPR.CATEGORIA_CATASTO CATEGORIA_CATASTO_LIQ
   , OGPR.CLASSE_CATASTO CLASSE_CATASTO_LIQ
   , OGPR.TIPO_OGGETTO TIPO_OGGETTO_LIQ
   , OGCO.PERC_POSSESSO PERC_POSSESSO_LIQ
   , OGCO.MESI_POSSESSO MESI_POSSESSO_LIQ
   , OGCO.MESI_ESCLUSIONE MESI_ESCLUSIONE_LIQ
   , OGCO.FLAG_RIDUZIONE FLAG_RIDUZIONE_LIQ
   , OGCO.MESI_RIDUZIONE MESI_RIDUZIONE_LIQ
   , OGCO.MESI_OCCUPATO MESI_OCCUPATO_LIQ
   , OGCO.DETRAZIONE DETRAZIONE_LIQ
   , OGIM_ACC.TIPO_ALIQUOTA TIPO_ALIQUOTA_LIQ
   , OGPR.OGGETTO_PRATICA_RIF OGGETTO_PRATICA_DIC
   , OGCO.COD_FISCALE
   , OGPR_ACC.PRATICA PRATICA_ACC
   , OGIM_ACC.TIPO_RAPPORTO TIPO_RAPPORTO_LIQ
   , PRTR.DATA DATA_LIQ
   from OGGETTI_CONTRIBUENTE OGCO
   , OGGETTI_PRATICA OGPR
   , PRATICHE_TRIBUTO PRTR
   , OGGETTI_CONTRIBUENTE OGCO_ACC
   , OGGETTI_IMPOSTA OGIM_ACC
   , OGGETTI_PRATICA OGPR_ACC
   , PRATICHE_TRIBUTO PRTR_ACC
  where OGCO.OGGETTO_PRATICA = OGPR.OGGETTO_PRATICA
 and PRTR.PRATICA = OGPR.PRATICA
 and PRTR.DATA <= PRTR_ACC.DATA
 and PRTR.ANNO = PRTR_ACC.ANNO
 and PRTR.numero = (select max (PRTR_SUB.numero)
    from OGGETTI_PRATICA OGPR_SUB, PRATICHE_TRIBUTO PRTR_SUB
   where PRTR_SUB.PRATICA = OGPR_SUB.PRATICA
  and OGPR_SUB.OGGETTO_PRATICA = OGPR.OGGETTO_PRATICA
  and PRTR_SUB.DATA = PRTR.DATA
  and PRTR_SUB.ANNO = PRTR.ANNO
  and PRTR_SUB.TIPO_PRATICA = 'L'
  and PRTR_SUB.DATA_NOTIFICA is not null
  and NVL(STATO_ACCERTAMENTO,'D')='D')
 and OGPR.OGGETTO_PRATICA_RIF = OGPR_ACC.OGGETTO_PRATICA_RIF
 and OGPR_ACC.PRATICA = PRTR_ACC.PRATICA
 and OGIM_ACC.OGGETTO_PRATICA = OGPR_ACC.OGGETTO_PRATICA
 and OGIM_ACC.ANNO = PRTR_ACC.ANNO
 and OGIM_ACC.COD_FISCALE = OGCO_ACC.COD_FISCALE
 and OGCO_ACC.COD_FISCALE = OGCO.COD_FISCALE
 and OGCO_ACC.OGGETTO_PRATICA = OGPR_ACC.OGGETTO_PRATICA
 and PRTR_ACC.TIPO_PRATICA = 'A';
comment on table LIQUIDAZIONE_OGPR_ACC is 'LIOA - Liquidazione OGPR ACC';

