--liquibase formatted sql 
--changeset abrandolini:20250326_152401_oggetti_tasi stripComments:false runOnChange:true 
 
create or replace force view oggetti_tasi as
select OGGETTI_CONTRIBUENTE.COD_FISCALE, PRATICHE_TRIBUTO.ANNO,
OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA, OGGETTI_CONTRIBUENTE.PERC_POSSESSO,
OGGETTI_CONTRIBUENTE.MESI_POSSESSO, OGGETTI_CONTRIBUENTE.MESI_ESCLUSIONE,
OGGETTI_CONTRIBUENTE.MESI_RIDUZIONE, OGGETTI_CONTRIBUENTE.DETRAZIONE,
OGGETTI_CONTRIBUENTE.MESI_ALIQUOTA_RIDOTTA, OGGETTI_CONTRIBUENTE.FLAG_POSSESSO,
OGGETTI_CONTRIBUENTE.FLAG_ESCLUSIONE, OGGETTI_CONTRIBUENTE.FLAG_RIDUZIONE,
OGGETTI_CONTRIBUENTE.FLAG_AB_PRINCIPALE, OGGETTI_CONTRIBUENTE.FLAG_AL_RIDOTTA,
OGGETTI_PRATICA.NUM_ORDINE, OGGETTI_PRATICA.IMM_STORICO,
OGGETTI_PRATICA.CATEGORIA_CATASTO, OGGETTI_PRATICA.CLASSE_CATASTO,
OGGETTI_PRATICA.VALORE, OGGETTI_PRATICA.TITOLO, OGGETTI_PRATICA.ESTREMI_TITOLO,
OGGETTI_PRATICA.FLAG_FIRMA, OGGETTI_PRATICA.MODELLO, OGGETTI_PRATICA.FONTE,
OGGETTI_PRATICA.OGGETTO_PRATICA_RIF, PRATICHE_TRIBUTO.PRATICA,
PRATICHE_TRIBUTO.TIPO_PRATICA, PRATICHE_TRIBUTO.DATA, OGGETTI_PRATICA.OGGETTO
from OGGETTI_CONTRIBUENTE, OGGETTI_PRATICA, PRATICHE_TRIBUTO
where OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA = OGGETTI_PRATICA.OGGETTO_PRATICA
and OGGETTI_PRATICA.PRATICA = PRATICHE_TRIBUTO.PRATICA
and PRATICHE_TRIBUTO.TIPO_TRIBUTO = 'TASI';
comment on table OGGETTI_TASI is 'OGSI';

