--liquibase formatted sql 
--changeset abrandolini:20250326_152401_oggetti_storici stripComments:false runOnChange:true 
 
create or replace force view oggetti_storici as
select OGGETTI_CONTRIBUENTE.COD_FISCALE, PRATICHE_TRIBUTO.ANNO,
OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA, OGGETTI_PRATICA.TRIBUTO,
OGGETTI_PRATICA.CATEGORIA, OGGETTI_PRATICA.TIPO_TARIFFA,
OGGETTI_CONTRIBUENTE.DATA_DECORRENZA, OGGETTI_CONTRIBUENTE.DATA_CESSAZIONE,
OGGETTI_PRATICA.VALORE, OGGETTI_PRATICA.CONSISTENZA, OGGETTI_PRATICA.OGGETTO,
PRATICHE_TRIBUTO.PRATICA, PRATICHE_TRIBUTO.TIPO_TRIBUTO,
PRATICHE_TRIBUTO.TIPO_PRATICA, PRATICHE_TRIBUTO.DATA
from OGGETTI_CONTRIBUENTE, OGGETTI_PRATICA, PRATICHE_TRIBUTO
where PRATICHE_TRIBUTO.TIPO_EVENTO in ('I','V','U');
comment on table OGGETTI_STORICI is 'OGST - Oggetti storici per contribuente';

