--liquibase formatted sql 
--changeset abrandolini:20250326_152401_oggetti_tosap stripComments:false runOnChange:true 
 
create or replace force view oggetti_tosap as
select OGGETTI_CONTRIBUENTE.COD_FISCALE, PRATICHE_TRIBUTO.ANNO,
OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA, OGGETTI_PRATICA.OGGETTO_PRATICA_RIF,
OGGETTI_CONTRIBUENTE.DATA_DECORRENZA, OGGETTI_CONTRIBUENTE.DATA_CESSAZIONE,
OGGETTI_PRATICA.TRIBUTO, OGGETTI_PRATICA.CATEGORIA, OGGETTI_PRATICA.TIPO_TARIFFA,
OGGETTI_PRATICA.CONSISTENZA, OGGETTI_PRATICA.NUM_CONCESSIONE,
OGGETTI_PRATICA.DATA_CONCESSIONE, OGGETTI_PRATICA.INIZIO_CONCESSIONE,
OGGETTI_PRATICA.FINE_CONCESSIONE, OGGETTI_PRATICA.LARGHEZZA,
OGGETTI_PRATICA.PROFONDITA, OGGETTI_PRATICA.COD_PRO_OCC,
OGGETTI_PRATICA.COD_COM_OCC, OGGETTI_PRATICA.INDIRIZZO_OCC,
OGGETTI_PRATICA.DA_CHILOMETRO, OGGETTI_PRATICA.A_CHILOMETRO,
OGGETTI_PRATICA.LATO, PRATICHE_TRIBUTO.PRATICA, PRATICHE_TRIBUTO.TIPO_PRATICA,
PRATICHE_TRIBUTO.DATA, OGGETTI_PRATICA.OGGETTO
from OGGETTI_PRATICA, OGGETTI_CONTRIBUENTE, PRATICHE_TRIBUTO
where OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA = OGGETTI_PRATICA.OGGETTO_PRATICA
and OGGETTI_PRATICA.PRATICA = PRATICHE_TRIBUTO.PRATICA
and PRATICHE_TRIBUTO.TIPO_TRIBUTO = 'TOSAP';
comment on table OGGETTI_TOSAP is 'OGTO - Oggetti contribuente TOSAP';

