--liquibase formatted sql 
--changeset abrandolini:20250326_152401_oggetti_tarsu stripComments:false runOnChange:true 
 
create or replace force view oggetti_tarsu as
select OGGETTI_CONTRIBUENTE.COD_FISCALE, PRATICHE_TRIBUTO.ANNO,
OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA, OGGETTI_PRATICA.CATEGORIA_CATASTO,
OGGETTI_PRATICA.CLASSE_CATASTO, OGGETTI_PRATICA.OGGETTO_PRATICA_RIF,
OGGETTI_CONTRIBUENTE.INIZIO_OCCUPAZIONE, OGGETTI_CONTRIBUENTE.FINE_OCCUPAZIONE,
OGGETTI_CONTRIBUENTE.DATA_DECORRENZA, OGGETTI_CONTRIBUENTE.DATA_CESSAZIONE,
OGGETTI_PRATICA.TRIBUTO, OGGETTI_PRATICA.CATEGORIA, OGGETTI_PRATICA.TIPO_TARIFFA,
OGGETTI_PRATICA.CONSISTENZA, PRATICHE_TRIBUTO.PRATICA,
PRATICHE_TRIBUTO.TIPO_PRATICA, PRATICHE_TRIBUTO.DATA, OGGETTI_PRATICA.OGGETTO
from OGGETTI_CONTRIBUENTE, OGGETTI_PRATICA, PRATICHE_TRIBUTO
where OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA = OGGETTI_PRATICA.OGGETTO_PRATICA
and OGGETTI_PRATICA.PRATICA = PRATICHE_TRIBUTO.PRATICA
and PRATICHE_TRIBUTO.TIPO_TRIBUTO = 'TARSU';
comment on table OGGETTI_TARSU is 'OGTA - Oggetti contribuente TARSU';

