--liquibase formatted sql 
--changeset abrandolini:20250326_152401_oggetti_iciap stripComments:false runOnChange:true 
 
create or replace force view oggetti_iciap as
select OGGETTI_CONTRIBUENTE.COD_FISCALE, PRATICHE_TRIBUTO.ANNO,
OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA, OGGETTI_PRATICA.OGGETTO_PRATICA_RIF,
OGGETTI_PRATICA.CONSISTENZA, OGGETTI_PRATICA.SETTORE, OGGETTI_PRATICA.CLASSE_SUP,
OGGETTI_PRATICA.IMPOSTA_BASE, OGGETTI_PRATICA.IMPOSTA_DOVUTA,
PRATICHE_TRIBUTO.PRATICA, PRATICHE_TRIBUTO.TIPO_PRATICA, PRATICHE_TRIBUTO.DATA,
OGGETTI_PRATICA.OGGETTO
from OGGETTI_PRATICA, OGGETTI_CONTRIBUENTE, PRATICHE_TRIBUTO
where OGGETTI_CONTRIBUENTE.OGGETTO_PRATICA = OGGETTI_PRATICA.OGGETTO_PRATICA
and OGGETTI_PRATICA.PRATICA = PRATICHE_TRIBUTO.PRATICA
and PRATICHE_TRIBUTO.TIPO_TRIBUTO = 'ICIAP';
comment on table OGGETTI_ICIAP is 'OGIP - Oggetti contribuente ICIAP';

