--liquibase formatted sql 
--changeset abrandolini:20250326_152401_web_maggiori_detrazioni stripComments:false runOnChange:true 
 
CREATE OR REPLACE FORCE VIEW WEB_MAGGIORI_DETRAZIONI AS
SELECT
    COD_FISCALE
  , TIPO_TRIBUTO
  , ANNO
  , MOTIVO_DETRAZIONE AS MOT_DETRAZIONE
  , DETRAZIONE
  , NOTE
  , DETRAZIONE_ACCONTO
  , DETRAZIONE_BASE
  , FLAG_DETRAZIONE_POSSESSO
  , TIPO_TRIBUTO || LPAD(TO_CHAR(MOTIVO_DETRAZIONE), 2, '0') ID_MOTIVO_DETRAZIONE
FROM
  MAGGIORI_DETRAZIONI;
comment on table WEB_MAGGIORI_DETRAZIONI is 'WEB_MAGGIORI_DETRAZIONI';

