--liquibase formatted sql 
--changeset abrandolini:20250326_152401_web_proprietari_catasto_urbano stripComments:false runOnChange:true 
 
CREATE OR REPLACE FORCE VIEW WEB_PROPRIETARI_CATASTO_URBANO AS
SELECT DISTINCT FABB.ID_IMMOBILE,
                SOGG.ID_SOGGETTO ID_SOGGETTO,
                SOGG.TIPO_SOGGETTO TIPO_SOGGETTO,
                RTRIM(LTRIM(SOGG.COGNOME)) || ' ' ||
                RTRIM(LTRIM(SOGG.NOME)) COGNOME_NOME,
                '' DES_COM_SEDE,
                '' SIGLA_PRO_SEDE,
                LTRIM(TITO.ID_CODICE_DIRITTO) COD_TITOLO,
                RTRIM(LTRIM(DIRI.DESCRIZIONE)) DES_DIRITTO,
                RTRIM(LTRIM(LTRIM(TITO.QUOTA_NUMERATORE, '0'))) NUMERATORE,
                RTRIM(LTRIM(LTRIM(TITO.QUOTA_DENOMINATORE, '0'))) DENOMINATORE,
                RTRIM(LTRIM(TITO.TITOLO_NON_CODIFICATO)) DES_TITOLO,
                TITO.DATA_VALIDITA_AL DATA_VALIDITA,
                TITO.DATA_VALIDITA_AL DATA_FINE_VALIDITA,
                SOGG.DATA_NASCITA DATA_NAS,
                DECODE(STAT.DENOMINAZIONE,
                       '',
                       COMU.DENOMINAZIONE,
                       STAT.DENOMINAZIONE) DES_COM_NAS,
                PROV.SIGLA SIGLA_PRO_NAS,
                SOGG.CODICE_FISCALE COD_FISCALE,
                FABB.TIPO_IMMOBILE,
                TITO.PARTITA,
                SOGG.COGNOME COGNOME,
                SOGG.NOME NOME,
                SOGG.CODICE_FISCALE CODICE_FISCALE
  FROM AD4_STATI_TERRITORI   STAT,
       AD4_COMUNI            COMU,
       AD4_PROVINCIE         PROV,
       WEB_CC_CODICI_DIRITTO DIRI,
       WEB_CC_TITOLARITA     TITO,
       WEB_CC_FABBRICATI     FABB,
       WEB_CC_SOGGETTI       SOGG
 WHERE STAT.STATO_TERRITORIO(+) = COMU.PROVINCIA_STATO
   AND COMU.SIGLA_CFIS(+) = SOGG.LUOGO_NASCITA
   AND COMU.DATA_SOPPRESSIONE IS NULL
   AND PROV.PROVINCIA(+) = COMU.PROVINCIA_STATO
   AND DIRI.CODICE(+) = TITO.ID_CODICE_DIRITTO
   AND TITO.ID_SOGGETTO = SOGG.ID_SOGGETTO
   AND TITO.ID_FABBRICATO = FABB.ID_FABBRICATO;
comment on table WEB_PROPRIETARI_CATASTO_URBANO is 'WEB_PROPRIETARI_CATASTO_URBANO';

