--liquibase formatted sql 
--changeset abrandolini:20250326_152401_web_tariffe stripComments:false runOnChange:true 
 
CREATE OR REPLACE FORCE VIEW WEB_TARIFFE
(ID_TARIFFA, TRIBUTO, CATEGORIA, ANNO, TIPO_TARIFFA, 
DESCRIZIONE, TARIFFA, PERC_RIDUZIONE, LIMITE, TARIFFA_SUPERIORE, 
LIMITE_PREC, TARIFFA_PREC, TARIFFA_SUPERIORE_PREC, TARIFFA_QUOTA_FISSA, FLAG_TARIFFA_BASE, 
RIDUZIONE_QUOTA_FISSA, RIDUZIONE_QUOTA_VARIABILE, ID_CATEGORIA, ENTE, TIPOLOGIA_TARIFFA, 
TIPOLOGIA_SECONDARIA, FLAG_NO_DEPAG)
AS 
select ID_TARIFFA,
       TRIBUTO,
       CATEGORIA,
       ANNO,
       TIPO_TARIFFA,
       DESCRIZIONE,
       TARIFFA,
       PERC_RIDUZIONE,
       LIMITE,
       TARIFFA_SUPERIORE,
       LIMITE_PREC,
       TARIFFA_PREC,
       TARIFFA_SUPERIORE_PREC,
       TARIFFA_QUOTA_FISSA,
       FLAG_TARIFFA_BASE,
       RIDUZIONE_QUOTA_FISSA,
       RIDUZIONE_QUOTA_VARIABILE,
       ID_CATEGORIA,
       ENTE,
       TIPOLOGIA_TARIFFA,
       TIPOLOGIA_SECONDARIA,
       FLAG_NO_DEPAG
  from TARIFFE
/
