--liquibase formatted sql 
--changeset abrandolini:20250326_152401_web_detrazioni_ogco stripComments:false runOnChange:true 
 
CREATE OR REPLACE FORCE VIEW WEB_DETRAZIONI_OGCO AS
SELECT
     COD_FISCALE
   , OGGETTO_PRATICA
   , ANNO
   , TIPO_TRIBUTO
   , MOTIVO_DETRAZIONE as MOT_DETRAZIONE
   , DETRAZIONE
   , NOTE
   , DETRAZIONE_ACCONTO
   , TIPO_TRIBUTO || LPAD(TO_CHAR(MOTIVO_DETRAZIONE), 2, '0') ID_MOTIVO_DETRAZIONE
FROM
    DETRAZIONI_OGCO;
comment on table WEB_DETRAZIONI_OGCO is 'WEB_DETRAZIONI_OGCO';

