--liquibase formatted sql 
--changeset abrandolini:20250326_152401_web_ruoli_oggetto stripComments:false runOnChange:true 
 
CREATE OR REPLACE FORCE VIEW WEB_RUOLI_OGGETTO AS
SELECT
RUOLO AS RUOLO_CONTRIBUENTE,
RUOLO,
COD_FISCALE,
SEQUENZA,
PRATICA,
ANNO_RUOLO,
TIPO_TRIBUTO,
TRIBUTO,
CONSISTENZA,
IMPORTO,
SEMESTRI,
DECORRENZA_INTERESSI,
MESI_RUOLO,
DATA_CARTELLA,
NUMERO_CARTELLA,
UTENTE,
DATA_VARIAZIONE,
NOTE,
OGGETTO,
OGGETTO_PRATICA,
CATEGORIA,
TIPO_TARIFFA,
OGGETTO_IMPOSTA,
IMPOSTA,
ADDIZIONALE_ECA,
MAGGIORAZIONE_ECA,
ADDIZIONALE_PRO,
IVA,
MAGGIORAZIONE_TARES,
IMPORTO_LORDO,
DA_MESE,
A_MESE,
GIORNI_RUOLO
FROM RUOLI_OGGETTO;
comment on table WEB_RUOLI_OGGETTO is 'WEB_RUOLI_OGGETTO';

